1105 f F_PP_MEM "PP1105F - Probleme memoire.\n"
1110 f F_PP_ALLOC "PP1110F - %s : Probleme d'allocation memoire.\n"
1120 f F_PP_READ "PP1120F - Erreur de lecture du membre %s. %s\n"
1121 f F_PP_STAT "PP1121F - Impossible d'obtenir des info sur le fichier\
 %s. %s\n"
1122 e E_PP_DIR  "PP1122E - %s est une directory et non un fichier.\n"
1125 f F_PP_CHPARM "PP1125F - Erreur de syntaxe dans le champ PARM.\n"
1130 f F_PP_OPEN1 "PP1130F - Erreur d 'ouverture du fichier \
sequentiel: %s\n"
1135 f F_PP_OPEN2 "PP1135F - Erreur d'ouverture du source a \
preprocesser. Membre: %s - DDNAME: %s\n"
1136 e E_PP_OPEN3 "PP1136E - Probleme d'ouverture du membre %s sur \
le ddname %s. %s.\n"
1140 f F_PP_WRITE "PP1140F - Erreur d'ecriture du source preprocesse.\n"
1141 f F_PP_IMBRIC "PP1141F - %4d ! %-8s ! %s trouve en dehors d'un \
bloc %s.\n"
1142 f F_PP_RULEIF "PP1142F - %4d ! %-8s ! Bloc IF ou bloc CASE pas \
ferme.\n"
1143 f F_PP_TYPLANG "PP1143F - Incompatibilite options du champ \
PARM : /TYPLANG et /NOLAN ou /LANG.\n"
1150 e E_PP_CLOSE "PP1150E - Erreur de fermeture de %s. %s\n"
1155 f E_PP_OPEN "PP1155F - Erreur d'ouverture de %s. %s\n"
1190 f F_PP_PBEDIT "PP1190F - Incompatibilite options du champ \
PARM : /NODEV et /EDIT.\n"
1200 f F_PP_DBLNODEV "PP1200F - Incompatibilite options du champ \
PARM : /NODEV et /NODEVU.\n"
1201 f E_PP_ENTILAN "PP1201F - Incompatibilite options du champ \
PARM : /LANG et /ENTITY.\n"
1202 f E_PP_ENTINLA "PP1202F - Incompatibilite options du champ \
PARM : /NOLAN et /ENTITY.\n"
1203 f E_PP_BUFFT98 "PP1203F - Incompatibilite options du champ \
PARM : /NOBUF et /FT98.\n"
1204 f E_PP_LEVPARM "PP1204F - Incompatibilite options du champ \
PARM : /LEV et /NOLEV.\n"
1205 f E_PP_LANPARM "PP1205F - Incompatibilite options du champ \
PARM : /LANG et /NOLAN.\n"
1206 f E_PP_SYNTAX "PP1206F - %4d ! %-8s ! Erreur syntaxique: %s. %s\n"
1207 f E_PP_LEXICAL "PP1207F - %4d ! %-8s ! Etat: %s - Erreur lexicale : %s\n"
1208 e E_PP_OCHARAC "PP1208E - %4d ! %-8s ! La declaration d'un logique \
officiel n'est pas autorisee en dehors d'une macro dite Level: %s.\n"
1209 e E_PP_OAFFECT "PP1209E - %4d ! %-8s ! L'initialisation d'un logique \
officiel n'est autorisee que dans une macro dite Level: %s\n"
1210 e E_PP_INCL "PP1210E - %4d ! %-8s ! Fin d'instruction d'Include \
attendue.\n"
1211 e E_PP_CASE "PP1211E - %4d ! %-8s ! Fin d'instruction Case \
attendue.\n"
1212 e E_PP_VALCASE "PP1212E - %4d ! %-8s ! Fin d'instruction Case attendue.\n"
1213 e E_PP_EXPO "PP1213E - %4d ! %-8s ! Condition officielle attendue.\n"
1214 e E_PP_EXPP "PP1214E - %4d ! %-8s ! Condition personnelle attendue.\n"
1215 e E_PP_DECLO "PP1215E - %4d ! %-8s ! Declaration de flag officiel \
attendu.\n"
1216 e E_PP_DECLP "PP1216E - %4d ! %-8s ! Declaration de flag personnel\
 attendu.\n"
1217 e E_PP_AFCTO "PP1217E - %4d ! %-8s ! Affectation de flag officiel\
attendue.\n"
1218 e E_PP_AFCTP "PP1218E - %4d ! %-8s ! Affectation de flag personnel \
attendue.\n"
1219 e E_PP_LEVINCLUD "PP1219E - Macro level a inclure non trouvee : %s`n"
1220 w E_PP_INCLUD "PP1220W - %4d ! %-8s ! Macro a inclure non trouvee : %s\n"
1221 e E_PP_NOMMAC "PP1221E - %4d ! %-8s ! Nom de macro pas compatible MVS.\n"
1222 e E_PP_NOMMBR "PP1222E - %4d ! %-8s ! Nom de membre pas compatible MVS.\n"
1224 e E_PP_CHNULL "PP1224E - %4d ! %-8s ! Substitution de chaine nulle\
 interdit.\n"
1225 e E_PP_EVAL "PP1225E - %4d ! %-8s ! Evaluation du flag impossible: %s\n"
1230 e E_PP_FLAJOUT "PP1230E - %4d ! %-8s ! Ajout du flag: %s de type: %s \
impossible.\n"
1235 i E_PP_FLAGBIS "PP1235W - %4d ! %-8s ! Nom: %s, Type: %s - \
Redeclaration du flag.\n"
1240 e E_PP_FLTYPE "PP1240E - %4d ! %-8s ! Nom: %s, Type: %s - Ce flag \
existe deja sous un autre type.\n"
1247 i E_PP_FLDECL "PP1247I - %4d ! %-8s ! Nom: %s, Type: %s - Le flag n'a \
pas ete declare.\n"
1250 e E_PP_LNGSUB "PP1250E - %4d ! %-8s ! Coupure de ligne impossible \
(suite a un reformattage).\n"
1255 e E_PP_EVALOR "PP1255E - %4d ! %-8s ! Impossible d'evaluer la \
condition .OR.\n"
1260 e E_PP_EVALAND "PP1260E - %4d ! %-8s ! Impossible d'evaluer la \
condition .AND.\n"
1265 e E_PP_EVALNOT "PP1265E - %4d ! %-8s ! Impossible d'evaluer le .NOT.\n"
1271 e E_PP_EVALCASE "PP1271E - %4d ! %-8s ! Evaluation du CASE a \
Unknown.\n"
1273 e W_PP_CONDUNK "PP1273E - %4d ! %-8s ! Condition evaluee a \
Unknown : %s\n"
1275 f E_PP_RECURS "PP1275F - %4d ! %-8s ! Mac: %s - Inclusion recursive.\n"
1280 e E_PP_ENDCHN "PP1280E - %4d ! %-8s ! Fin de fichier inattendue.\n"
1285 e E_PP_ENDCOMC "PP1285E - %4d ! %-8s ! Fin de commentaire C attendue.\n"
1290 e E_PP_STRC "PP1290E - %4d ! %-8s ! Fin de string C attendue.\n"
1291 e E_PP_STRFORT "PP1291E - %4d ! %-8s ! Fin de string FORTRAN attendue.\n"
1292 e E_PP_LEXLANG "PP1292E - %4d ! %-8s ! Ligne de code de type %s pas \
correct.\n"
1293 w W_PP_RLINE "PP1293W - L'option RLINE n'est pas compatible avec \
les options /NOBUF et /NOFT7. La table de reference des lignes ne sera \
pas generee.\n"
1294 w W_PP_CLINE "PP1294W - L'option CLINE n'est pas compatible avec \
les options /NOBUF et /NOFT7. Les \"pragma line\" ne seront pas \
generes.\n"
1295 f F_PP_LDHEX "PP1295F - Impossible de lire en hexa la macro \
level compilee.\n"
1296 f F_PP_LDMEM "PP1296F - Erreur de lecture memoire de la %s\n."
1297 f F_PP_STORE "PP1297F - Erreur de stockage sur fichier de la %s\n."
1298 f F_PP_LEVDYN "PP1298F - Erreur de stockage dynamique de la macro \
level compilee en memoire.\n"
1301 w W_PP_LANG "PP1301W - Langage du champ Parm non reconnu: %c.\n"
1302 w W_PP_TYPLANG "PP1302W - Le langage (%s) reconnu par le prepro \
n'est pas celui attendu (%s)\n"
1305 w W_PP_LANGCLINE "PP1305W - Le langage %s a ete reconnu. L'option \
/CLINE n'est pas reconnue.\n"
1310 f W_PP_NOFIC "PP1310F - Aucun source n'a ete preprocesse.\n"
1315 i W_PP_FLREINI "PP1315I - %4d ! %-8s ! Nom: %s, Type: %s - \
Reinitialisation du flag.\n"
1320 i W_PP_GPREINI "PP1320I - %4d ! %-8s ! Nom: %s*, Type: %s - \
Reinitialisation du groupe.\n"
1325 i I_PP_VIDE "PP1325I - %s : le source preprocesse est vide.\n"
1330 i I_PP_TABOPER "PP1330I - %4d ! %-8s ! Un flag de type STRING \
de valeur : %s est compare a un flag de type BOOLEAN de valeur %s\n"
