105	e	E_OPEN	"CP0105E - Ouverture de %s impossible. %s\n"                       
110	e	E_CLOSE "CP0110E - Fermeture de %s impossible. %s\n"                      
115 e E_FLAG "CP0115E - Le flag de livraison a ete reference deux fois  .\n"    
120 e E_MBR "CP0120E - L'option /MBR ne peut etre utilisee avec les \           
options /MBROLD et /MBRNEW.\n"                                                  
135	e	E_CHAINE	"CP0135E - L'un des sources preprocesses est vide.\n"            
140	e	E_PREPRO	"CP0140E - Probleme Prepro - Champ Parm : %s\n"                  
145	e	E_LANG "CP0145E - Les langages reconnus par le prepro sont \              
differents: %s et %s.\n"                                                        
150 f F_MEM "CP0150F - Probleme d'allocation memoire.\n"                        
