

*****************************************************************
*       ERREURS LIENS LOGIQUES                                  *
*****************************************************************

100     e       E_F77_LOG_ENDDO
"File \"%s\", line %d, \
  END DO statement appears outside of a DO-loop or a DO WHILE-loop\n"

120     e       E_F77_LOG_ELSE
"File \"%s\", line %d, \
  ELSE statement or ELSE IF statement appears outside of a IF block\n"

130     e       E_F77_LOG_ENDIF
"File \"%s\", at line %d, \
  END IF statement appears outside of a IF block\n"

140     e       E_F77_LOG_IF
"File \"%s\", line %d, \
  IF block is not closed\n"

150     e       E_F77_LOG_DO
"File \"%s\", line %d, \
  DO-loop or DO WHILE-loop is not closed\n"

160     e       E_F77_LOG_LABEL
"File \"%s\", line %d, \
  statement label \"%d\" is referenced but not defined\n"

170     w       W_F77_LOG_LABEL
"File \"%s\", line %d, \
  statement label \"%d\" is defined but not referenced\n"

180     f       F_F77_LOG_NOMEM
"Not enough memory\n"

