*****************************************************************
*								*
*	Messages du composant "inter"				*
*								*
*****************************************************************

0	f	E_INTER_NOMEM	"Not enough memory\n"
1	e	E_INTER_TYPE	"Incompatible types\n"
2	e	E_INTER_TYPESZ	"Incompatible type sizes\n"
3	e	E_INTER_NDIM	"Incompatible number of dimensions\n"
4	e	E_INTER_DIM	"Incompatible dimensions\n"
5	e	E_INTER_NAME	"Description \"%s\": descriptions come from\
 different units \"%s\" and \"%s\"\n"
6	e	E_INTER_UNIT	"Description \"%s\": different kind of program\
 unit\n"
7	e	E_INTER_NARG	"Description \"%s\": different number of\
 arguments\n"
8	e	E_INTER_CLASS	"Description \"%s\": incompatible classes for\
 argument %d\n"
9	e	E_INTER_FTYPE	"Description \"%s\": incompatible function\
 type\n"
10	e	E_INTER_FTYPESZ	"Description \"%s\": incompatible function type\
 size\n"
11	e	E_INTER_ATYPE	"Description \"%s\": incompatible type for\
 argument %d\n"
12	e	E_INTER_ATYPESZ	"Description \"%s\": incompatible type size\
 for argument %d\n"
13	e	E_INTER_AMODE	"Description \"%s\": incompatible mode for\
 argument %d\n"
14	e	E_INTER_ANDIM	"Description \"%s\": incompatible number of\
 dimensions for argument %d\n"
15	e	E_INTER_ADIM	"Description \"%s\": incompatible dimension\
 for argument %d\n"
