*****************************************************************
*								*
*	Messages du composant "libxref"				*
*								*
*****************************************************************

0	e	E_LX_OPEN	"Unable to open description or reference file \
\"%s\"\n"
1	e	E_LX_CREATE	"Unable to create description or reference \
file \"%s\"\n"
2	e	E_LX_CLOSE	"Unable to close a description or reference \
file\n"
3	e	E_LX_READ	"Error while reading a description or \
reference file\n"
4	e	E_LX_WRITE	"Error while writing a description or \
reference file\n"
5	e	E_LX_CORRUPT	"A description or reference file is corrupted\n"
6	e	E_LX_EOF	"Premature end of a description or reference \
file\n"
7	e	E_LX_DELETE	"Unable to delete description or reference \
file \"%s\"\n"
