*****************************************************************
*								*
*	Messages du composant "lib"				*
*								*
*****************************************************************

0	e	E_LIB_OPEN	"Unable to open description file \"%s\"\n"
1	e	E_LIB_CREATE	"Unable to create description file \"%s\"\n"
2	e	E_LIB_CLOSE	"Unable to close description file \"%s\"\n"
3	e	E_LIB_INPUT	"Error reading description file \"%s\"\n"
4	e	E_LIB_OUTPUT	"Error writing description file \"%s\"\n"
5	e	E_LIB_CORRUPT	"Description file \"%s\" is corrupted\n"
6	e	E_LIB_EOF	"Premature end of description file \"%s\"\n"
7	e	E_LIB_DELETE	"Unable to delete description file \"%s\"\n"
