*****************************************************************
*								*
*	Messages du composant "main"				*
*								*
*****************************************************************

0	e	E_MAIN_MISSING_OPT	"Missing option\n"
1	e	E_MAIN_INVALID_OPT	"Invalid option \"%c\"\n"
2	e	E_MAIN_ARGUMENT		"Wrong number of arguments\n"
3	e	E_MAIN_NAME_LEN		"Function or subroutine name \"%s\" is\
too long in parameter file\n"
4	e	E_MAIN_LIB		"Missing description \"%s\"\n"
5	w	E_MAIN_LIBEXIST		"Description \"%s\" already exists\n"
6	i	I_MAIN_SRC_BEGIN	"File \"%s\": beginning of analysis\n"
7	i	I_MAIN_GOODEND		"File \"%s\": successful analysis\n\n"
8	i	I_MAIN_BADEND		"File \"%s\": analysis failed\n\n"
9	i	I_MAIN_PASS		"Pass number %d\n\n"
10	i	I_MAIN_LIB_BEGIN	"Description \"%s\": beginning of \
processing\n"
11	h	H_MAIN_HELP		"Usage: WA0SAG -r[acdi]\n\
                    WA0SAG -g[c]\n\
                    WA0SAG -u[rafdxce]\n\
                    WA0SAG -h\n"
