

********************************************************************
*                                                                  *
*  MESSAGES CONCERNANT LES DECLARATIONS IMPLICITES                 *
*                                                                  *
********************************************************************

100     w       E_RDC_IMPL_IMPL
"File \"%s\", unit \"%s\", \
implicit Fortran declaration for variable \"%s\", \
its type is \"%s\" and  its length is %d\n\n"

110     w       E_RDC_IMPL_DEF
"File \"%s\", unit \"%s\", \
variable \"%s\" is declared according to an IMPLICIT statement, \
its type is \"%s\" and  its length is %d\n\n"

