
********************************************************************
*                                                                  *
*  MESSAGES CONCERNANT LES VARIABLES NON INITIALISEES              *
*                                                                  *
********************************************************************

100     e       E_RDC_INIT_MSG
"File \"%s\", unit \"%s\", line %d, \"%s\" is unset  \
corresponding path is the following :  "

110     i       E_RDC_INIT_PAIR
"%d->%d,"

120     i       E_RDC_INIT_ELE
"%d,"

130     i       E_RDC_INIT_SEMIEND
""

140     i       E_RDC_INIT_END
"\n\n"

150     f       F_RDC_INIT_NOMEM
"Not enough memory\n"
