
********************************************************************
*                                                                  *
*  MESSAGES CONCERNANT LA GENERATION AUTOMATIQUE DES DESCRIPTIONS  *
*                                                                  *
********************************************************************

100     e       E_RDC_GEN_OVERDESC
"File \"%s\", \
overwritting of the user description \"%s\" is unauthorized\n\n"

110     w       E_RDC_GEN_UNDEF
"File \"%s\", \
argument \"%s\" is never used in unit \"%s\"\n\n"

120     i       E_RDC_GEN_DESC
"File \"%s\", \
description \"%s\" is generated\n\n"

130     w       W_RDC_GEN_NODESC
"File \"%s\", \
\"%s\" is a program or a blockdata, so no description is \
generated \n\n"

