*****************************************************************
*								*
*	Messages du composant "spec"				*
*								*
*****************************************************************

0	e	E_SPEC_INVAL	"Internal error\n"
1	e	E_SPEC_OPEN	"Unable to open input file \"%s\"\n"
2	e	E_SPEC_CLOSE	"Unable to close file \"%s\"\n"
3	e	E_SPEC_CREATE	"Unable to create output file \"%s\"\n"
4	e	E_SPEC_WRITE	"Write error\n"
5	e	E_SPEC_OUTPUT	"Error writing output file \"%s\"\n"
6	e	E_SPEC_LEX	"At line %d: illegal character \"%s\"\n"
7	e	E_SPEC_SYNT	"At line %d: syntax error near \"%s\"\n"
8	e	E_SPEC_TYPE	"At line %d: type \"%s\" is unknown\n"
9	e	E_SPEC_DIM	"At line %d: the array has too many dimensions\
\n"
10	e	E_SPEC_DECL	"At line %d: unexpected declaration of \"%s\"\n"
11	e	E_SPEC_UNDECL	"The type of argument or function \"%s\" is \
unknown\n"
12	e	E_SPEC_REDEF	"At line %d: argument \"%s\" is declared twice\
\n"
13	e	E_SPEC_WGTYPE	"At line %d: a function cannot return an array\
\n"
14	e	E_SPEC_REDEFD	"At line %d: multiple use of keyword \
\"DIMENSION\"\n"
15	e	E_SPEC_REDEFI	"At line %d: multiple use of keyword \
\"INTENT\"\n"
