*****************************************************************
*								*
*	Messages du composant "util"				*
*								*
*****************************************************************


*****************************************************************
*	Messages generaux					*
*****************************************************************
0	f	E_NOMEM		"Not enough memory\n"


*****************************************************************
*	Gestion des fichiers					*
*****************************************************************
10	e	E_FILE_DDNAME	"DDNAME \"%s\" is undefined\n"
11	e	E_FILE_OPEN	"Unable to open or create file \"%s\" with \
DDNAME \"%s\"\n"
12	e	E_FILE_CLOSE	"Unable to close a file\n"
13	e	E_FILE_WHICH	"Unable to find file \"%s\" with \
DDNAME \"%s\"\n"
14	e	E_FILE_DELETE	"Unable to remove file \"%s\" with \
DDNAME \"%s\"\n"
15	e	E_FILE_DIR	"Unable to open directory \"%s\"\n"
16	e	E_FILE_PDS	"Unable to open PDS \"%s\"\n"


*****************************************************************
*	Gestion des noms					*
*****************************************************************
20	e	E_NAME_LEN	"Identifier too long\n"


*****************************************************************
*	Gestion des ensembles de chaines de caracteres		*
*****************************************************************
30	e	E_SS_LEN	"String too long\n"
31	e	E_SS_NODESC	"Not enough string set identifier\n"



*****************************************************************
*	Gestion des petits objets en memoire			*
*****************************************************************
40	e	E_OM_NULL	"Object type has null size\n"
41	e	E_OM_NODESC	"Not enough object memory identifier\n"
