*****************************************************************
*								*
*	Messages du composant "xref"				*
*								*
*****************************************************************

0	e	E_XR_NOMEM	"Not enough memory in XREF component\n"
1	e	E_XR_OPEN	"Unable to open reference file \"%s\"\n"
2	e	E_XR_CREATE	"Unable to create reference file \"%s\"\n"
3	e	E_XR_CLOSE	"Unable to close reference file \"%s\"\n"
4	e	E_XR_INPUT	"Error reading reference file \"%s\"\n"
5	e	E_XR_OUTPUT	"Error writing reference file \"%s\"\n"
6	e	E_XR_CORRUPT	"Reference file \"%s\" is corrupted\n"
7	e	E_XR_EOF	"Premature end of reference file \"%s\"\n"
8	e	E_XR_NAME_LEN	"Entry name too long in parameter file\n"
9	e	E_XR_DELETE	"Unable to delete reference file \"%s\"\n"
10	i	I_XR_CALL	"\n\nList of subroutines or functions called:\n\
---------------------------------------\n"
11	i	I_XR_XREF	"\n\nList of calling subroutines or functions:\
\n----------------------------------------\n"
