#
# Specifications for Build step mkBSDoc
#
METACLASS_NAME = DocXMPublishHtm
#
DGM_GRAPH_PATH = MODDGM_GRAPHPATH_DOC
#
SOURCE_EXTENSION = RootMap.ditamap
# For Coverage tools
#
MOD_LINKWITH = $(MOD_LinkWith)
MOD_SRCLINKWITH = $(MOD_SrcLinkWith)
#
FILTER_AUDIENCE = $(DOC_AUDIENCE_FILTER)
FILTER_PRODUCT = $(DOC_PRODUCT_FILTER)
FILTER_PLATFORM = $(DOC_PLATFORM_FILTER)
#
DGM_VERSION = 1.01

DGM_DEPEND = MOD_LINKWITH MOD_SRCLINKWITH DOT_DOST DOT_XSL DGM_VERSION FILTER_AUDIENCE FILTER_PRODUCT FILTER_PLATFORM
# 
