#
# Specifications for Build step mkBSCabJar
#
CABJAR_WORKPATH = $(GLocal)/.tmp.$(CABJAR_ROOTNAME)
CABJAR_OBJLIST = $(OBJPATH)/.objects
#
CABJAR_LWLIST =  $(CABJAR_OBJLIST).lw
CABJAR_SRCLIST = $(CABJAR_OBJLIST).src
CABJAR_RESLIST = $(CABJAR_OBJLIST).res
CABJAR_SKELETON = $(CABJAR_OBJLIST).ske
#
CABJAR_CREATEDFILE = $(CABJAR_WORKPATH)/mkCabJar.createdfiles
#
CABJAR_ROOTNAME = $(PROGRAM_NAME:-MODNAME)
#
CABJAR = mkCabJarM
#
CABJAR_OPTS = $(RELEASE_STARTDATE:?"-name") $(RELEASE_STARTDATE) -name "$(CABJAR_ROOTNAME)" $(BUILD_MODE:+"-mode") $(BUILD_MODE) $(CABJAR_SIGN:?"-sign") $(VERSIONFILE:?"-version") $(VERSIONFILE) $(EMBED_VERSION:?"-embed_version") $(EMBED_VERSION) $(LOCAL_CABJARFLAGS)
CABJAR_OSX = $(PLUGIN_PKGINDEX:?"-pkg_index") $(PLUGIN_PKGINDEX) -pkg_src $(MOD_SrcPath)
#
CABJAR_COMMAND = $(CABJAR) $(CABJAR_OPTS) $(CABJAR_OSX) -input "$(CABJAR_LWLIST)" -include_src "$(CABJAR_SRCLIST)" -include_resource "$(CABJAR_RESLIST)" -msi_skeleton "$(CABJAR_SKELETON)"
#
#
DGM_VERSION = 1.0
#

