#
# Specifications for Build step mkBSVB
#
# ---------------------
#
TODOXMLASSEMBLYANDVERSIONINFOANDPOLICY=$(MkmkXMLASSEMBLYANDVERSIONINFOANDPOLICY:@"YES")
#
VB_TLBTOPAS_COMPILER = $(MkmkDELPHIDIR)\bin\tlibimp
VB_TLB_COMPILER = tlbexp
VB_RESOURCE_COMPILER = resgen
VB_COMPILEUR = vbc
VB_POLICY_COMPILER = al
#
VB_CONSOLE = /target:exe
VB_WINDOWS = $(DISABLE_CONSOLE:?"/target:winexe")
VB_DLL = /target:library
VB_EXE_TYPE = $(VB_WINDOWS:-VB_CONSOLE)
VB_EXE = $(CLR_EXE_TYPE:%+VB_EXE_TYPE)
VB_TARGET= $(VB_EXE:-VB_DLL)
#
VB_DEBUG = $(MKMK_DEBUG:+"/debug+")
VB_STDLIBSPATH = "/libpath:$(MkmkMSVCSHARPDIR)"
VB_STDLIBS = /r:"System.DirectoryServices.dll" /r:"System.Data.dll" /r:"System.XML.dll" /r:"System.EnterpriseServices.dll" /r:"System.Drawing.dll" /r:"System.Web.dll"  
VB_OPTS = $(VB_TARGET) /nologo $(LOCAL_VB_FLAGS) $(LOCAL_VBFLAGS) $(VB_STDLIBS) $(VB_STDLIBSPATH) $(VB_DEBUG)
#
# SET_OBJNAME, SET_TLBOBJNAME
#
VB_POLICY_COMMAND = "$(VB_POLICY_COMPILER)" /nologo
VB_TLBTOPAS_COMMAND = "$(VB_TLBTOPAS_COMPILER)" -A"_TLB" -P+ -R- "$(SET_TLBOBJNAME)"
VB_TLB_COMMAND = $(VB_TLB_COMPILER) /nologo /out:"$(SET_TLBOBJNAME)" "$(SET_OBJNAME)"
VB_RESOURCE_COMMAND = $(VB_RESOURCE_COMPILER) /compile
VB_COMMAND = $(VB_COMPILEUR) $(VB_OPTS) $(VB_LIBPATH) /out:"$(SET_OBJNAME)" $(VB_REFLIBS)
#
include mkBSSignToolDecl.mk
_SIGN_OBJNAME = $(SET_OBJNAME)
_SIGN_ACTIVATION = $(SIGN_ACTIVATION) $(MKMK_DISABLE_SIGNTOOL)
#
DGM_VERSION = 1.2
DGM_DEPEND = _SIGN_ACTIVATION MKSIGNMS_OPTS
#
MKMK_DGM_BEHAVIOUR=update
#
SCRIPT_COMMAND = VB_RESOURCE_COMMAND VB_COMMAND VB_TLB_COMMAND VB_TLBTOPAS_COMMAND\
	[1] [2] VB_POLICY_COMMAND MKSIGNMS_COMMAND
#
