#
# Specifications for Build step Doc
#
# ---------------------
#
CHECKPII_VERSION = 1.0
# CHECKPII_COMPILER = mkcheckpii

CHECKPII_COMPILER = TestLocale
CHECKPII_OPTS     = %SOURCE%
#
CHECKPII_COMMAND = $(CHECKPII_COMPILER) $(CHECKPII_OPTS)
#
CHECKPII_ACTIVATION = NO
#
#DGM_VERSION = 1.0
#

