#
# Specifications for Build step mkBSRMS
#
MKMK_DGM_BEHAVIOUR = update
#
RMSSDK_PATH = $(_MkmkRMSSDK_PATH:-MkmkRMSSDK_PATH)
RMS_MANIFESTGENERATOR = $(RMSSDK_PATH)\Genmanifest.exe
#
RMS_PREPROD_PRIVKEY = $(RMSSDK_PATH)\ISVTier5AppSigningPrivKey.dat
RMS_PREPROD_PUBKEY = $(RMSSDK_PATH)\ISVTier5AppSigningPubKey.dat
RMS_PREPROD_CHAIN = $(RMSSDK_PATH)\ISVTier5AppSignSDK_Client.xml
#
RMS_PREPROD_MCFPATH = $(GLocal)\preproduction.mcf
RMS_PREPROD_MANIFEST = $(RMSPREPROD_PATHNAME)
#
RMS_PREPROD_MCF = \
 AUTO-GUID "$(RMS_PREPROD_PRIVKEY)" \
 MODULELIST \
 REQ HASH "$(RTPATHNAME)" \
 REQ NOHASH "%SystemRoot%\system32\msdrm.dll" \
 POLICYLIST \
 INCLUSION PUBLICKEY "$(RMS_PREPROD_PUBKEY)" \
 EXCLUSION
#
RMS_PREPROD_COMMAND = "$(RMS_MANIFESTGENERATOR)" -chain "$(RMS_PREPROD_CHAIN)" "$(RMS_PREPROD_MCFPATH)" "$(RMS_PREPROD_MANIFEST)"
#
RMS_PROD_PRIVKEY = $(MkmkRMS_PROD_PRIVKEY)
RMS_PROD_PUBKEY = $(MkmkRMS_PROD_PUBKEY)
RMS_PROD_CHAIN = $(MkmkRMS_PROD_CHAIN)
#
RMS_PROD_MCFPATH = $(GLocal)\production.mcf
RMS_PROD_MANIFEST = $(RMSPROD_PATHNAME)
# Create the production manifest if this macro is not empty
RMS_PROD_KEYS = $(RMS_PROD_PRIVKEY:+RMS_PROD_PUBKEY)
RMS_PROD_STARTER = $(RMS_PROD_KEYS:+RMS_PROD_CHAIN)
#
RMS_PROD_MCF = \
 AUTO-GUID "$(RMS_PROD_PRIVKEY)" \
 MODULELIST \
 REQ HASH "$(RTPATHNAME)" \
 REQ NOHASH "%SystemRoot%\system32\msdrm.dll" \
 POLICYLIST \
 INCLUSION PUBLICKEY "$(RMS_PROD_PUBKEY)" \
 EXCLUSION
#
RMS_PROD_COMMAND = "$(RMS_MANIFESTGENERATOR)" -chain "$(RMS_PROD_CHAIN)" "$(RMS_PROD_MCFPATH)" "$(RMS_PROD_MANIFEST)"
#
