# @(#) preprocess
# ----------------------
# Specifications for Build step mkBSCppManaged
# ----------------------
include mkBSCompilersPathDecl.mk
include mkBSSignToolDecl.mk
# ----------------------
#if (defined MK_BITMODE) && (MK_BITMODE == 64)
#rem: 64-bit mode
CSHARP_MACHINE = /MACHINE:X64
#else
#rem: 32-bit mode
CSHARP_MACHINE = /MACHINE:IX86
#endif
# ---------------------
TODOXMLASSEMBLYANDVERSIONINFOANDPOLICY=$(MkmkXMLASSEMBLYANDVERSIONINFOANDPOLICY:@"YES")
# ---------------------
CSHARP_TLBTOPAS_COMPILER = $(_MK_TLIBIMP_UTILPATH)
CSHARP_TLB_COMPILER = $(_MK_TLBEXP_UTILPATH)
CSHARP_CPP_COMPILER = $(_MK_CL_UTILPATH)
CSHARP_LINK_COMPILER = $(_MK_LINK_UTILPATH)
CSHARP_POLICY_COMPILER = $(_MK_AL_UTILPATH)
# ---------------------
CSHARP_CPP_DEFINED = /D"_WINDOWS_SOURCE" /D"_ENDIAN_LITTLE" /D"WINVER=0x0400" /D"UNICODE" /D"_UNICODE" /D"WIN32"
CSHARP_CPP_DEBUG = $(MKMK_DEBUG:+"/Od")
CSHARP_CPP_OPTIMIZE = $(OPTIMIZATION_CPP:-"/Og")
CSHARP_CPP_WARNING = $(MKMK_WARNING:+"/W3")
#
CSHARP_TLBTOPAS_OPTS = $(LOCAL_TLBTOPAS_FLAGS)
CSHARP_TLBTOPAS_COMMAND = "$(CSHARP_TLBTOPAS_COMPILER)" $(CSHARP_TLBTOPAS_OPTS) -A"_TLB" -P+ -R- "$(SET_TLBOBJNAME)"
#
CSHARP_TLB_OPTS = $(LOCAL_TLB_OPTS)
CSHARP_TLB_COMMAND = "$(CSHARP_TLB_COMPILER)" /nologo $(CSHARP_TLB_OPTS) /out:"$(SET_TLBOBJNAME)" "$(SET_OBJNAME)"
#
CSHARP_CPP_OPTS = $(LOCAL_CCFLAGS) $(CSHARP_CPP_DEFINED) $(CSHARP_CPP_DEBUG:-CSHARP_CPP_OPTIMIZE) $(CSHARP_CPP_WARNING:-"/W1") /Zi $(LOCAL_POST_CCFLAGS)
CSHARP_CPP_COMMAND = $(CSHARP_CPP_COMPILER) /nologo /clr /c $(CSHARP_CPP_OPTS)
#
CSHARP_LINK_OPTS = $(LOCAL_LDFLAGS) $(CLR_EXE_TYPE:%-"/DLL") /DEBUG /DEBUGTYPE:CV $(CSHARP_MACHINE) /FIXED:NO /FORCE:MULTIPLE $(SYS_LIBPATH) $(SYS_LIBS)
CSHARP_LINK_COMMAND = $(CSHARP_LINK_COMPILER) /NOLOGO $(CSHARP_LINK_OPTS) /OUT:"$(SET_OBJNAME)"
#
CSHARP_POLICY_OPTS = $(LOCAL_POLICY_FLAGS)
CSHARP_POLICY_COMMAND = "$(CSHARP_POLICY_COMPILER)" /nologo $(CSHARP_POLICY_OPTS)
#
# SET_OBJNAME, SET_TLBOBJNAME
#
CSHARP_OPTS = $(CSHARP_TLBTOPAS_OPTS) $(CSHARP_TLB_OPTS)\
	$(CSHARP_CPP_OPTS) $(CSHARP_LINK_OPTS) $(CSHARP_POLICY_OPTS)
#
_SIGN_OBJNAME = $(SET_OBJNAME)
_SIGN_ACTIVATION = $(SIGN_ACTIVATION) $(MKMK_DISABLE_SIGNTOOL)
#
DGM_VERSION = 1.0
DGM_DEPEND = _SIGN_ACTIVATION MKSIGNMS_OPTS
#
MKMK_DGM_BEHAVIOUR=update
#
SCRIPT_COMMAND = CSHARP_CPP_COMMAND CSHARP_LINK_COMMAND CSHARP_TLB_COMMAND CSHARP_TLBTOPAS_COMMAND\
	[1] [2] CSHARP_POLICY_COMMAND MKSIGNMS_COMMAND
#
