#
# Specifications for Build step mkBSMidl
#
include mkBSIdl_cmd.mk
#
FORCE_TYPELIB = $(MKMK_FORCE_TYPELIB)
#
TPLIB_CPL = $(IDL_CPL)
TPLIB_CREATEDFILE = $(TPLIB_CPL).createdfiles
#
TPLIB_SCOPE = -scope $(IDLSCOPE)
TPLIB_OPTS = $(LOCAL_IDLFLAGS) $(IDL_MKIDOPT) -native -filetype typelib $(IDLSCOPE:+TPLIB_SCOPE)
TPLIB_COMMAND = $(TPLIB_CPL) $(TPLIB_OPTS)
#
#TLBREGISTRATION_COMPILER = regtlib
#TLBREGISTRATION_COMMAND = "$(TLBREGISTRATION_COMPILER)"
#
DGM_DEPEND = FORCE_TYPELIB
DGM_VERSION = 1.0
#

