#
# Specifications for Build step mkBSDoc
#
METACLASS_NAME = DocCheckRTVDoc
#
DGM_GRAPH_PATH = MODDGM_GRAPHPATH_DOC
#
INHTM_PATH = $(DOCPATH)\@LANG@\$(MODNAME)
#
### PREFIX_DERIVED_PATH = $(DOCPATH)/ref
#
SOURCE_HTM = *.htm
#
DGM_VERSION = 1.01
DGM_DEPEND =
#
