#
# Specifications for Build step mkBSDoc
#
METACLASS_NAME = DocFromXml
#
DGM_GRAPH_PATH = MODDGM_GRAPHPATH_DOC
#
PREFIX_DERIVED_PATH = $(DOCPATH)/online$(LANG)/$(MODNAME)
#
MOD_LINKWITH = $(MOD_LinkWith)
#
SOURCE_EXTENSION = *.cnfxml
#
DGM_VERSION = 1.01
DGM_DEPEND = MOD_LINKWITH FROMXML_OPTS FROMXML_BUFFER
#
