#
# Specifications for Build step mkBSArchive
#
METACLASS_NAME = Archive
METACLASS_SOURCE = Compilation
#
DGM_GRAPH_PATH = MODDGM_GRAPHPATH
#
BUILT_TYPE = $(BUILT_OBJECT_TYPE)
OBJECTS_DELIVERED_PATH = $(INSTALL_PTO_TO)
#
DGM_DEPEND = AR_OPTS BUILT_TYPE
#
