# @(#) preprocess
# ----------------------
# Specifications for Build step mkBSJSharp
# ----------------------
include mkBSCompilersPathDecl.mk
include mkBSSignToolDecl.mk
# ----------------------
#if (defined MK_BITMODE) && (MK_BITMODE == 64)
#rem: 64-bit mode
JSHARP_PLATFORM = /platform:x64
#endif
# ---------------------
TODOXMLASSEMBLYANDVERSIONINFOANDPOLICY=$(MkmkXMLASSEMBLYANDVERSIONINFOANDPOLICY:@"YES")
# ---------------------
JSHARP_TLBTOPAS_COMPILER = $(_MK_TLIBIMP_UTILPATH)
JSHARP_TLB_COMPILER = $(_MK_TLBEXP_UTILPATH)
JSHARP_RESOURCE_COMPILER = $(_MK_RESGEN_UTILPATH)
JSHARP_COMPILEUR = $(_MK_VJC_UTILPATH)
JSHARP_POLICY_COMPILER = $(_MK_AL_UTILPATH)
# ---------------------
JSHARP_CONSOLE = /target:exe
JSHARP_WINDOWS = $(DISABLE_CONSOLE:?"/target:winexe")
JSHARP_DLL = /target:library
JSHARP_EXE_TYPE = $(JSHARP_WINDOWS:-JSHARP_CONSOLE)
JSHARP_EXE = $(CLR_EXE_TYPE:%+JSHARP_EXE_TYPE)
JSHARP_TARGET= $(JSHARP_EXE:-JSHARP_DLL)
#
JSHARP_WARNING = $(MKMK_WARNING:%-"/w:0")
JSHARP_DEBUG = $(MKMK_DEBUG:+"/debug+")
#
#JSHARP_STDLIBSPATH ="/libpath:$(MkmkMSVJSHARPDIR)" "/libpath:$(MkmkMSVJSHARPDIR)"
JSHARP_STDLIBS = /r:"vjslib.dll" /r:"System.DirectoryServices.dll"  /r:"System.Data.dll"  /r:"System.XML.dll"  /r:"System.EnterpriseServices.dll"  /r:"System.Drawing.dll"  /r:"System.Web.dll" 
#
JSHARP_TLBTOPAS_OPTS = $(LOCAL_TLBTOPAS_FLAGS)
JSHARP_TLBTOPAS_COMMAND = "$(JSHARP_TLBTOPAS_COMPILER)" $(JSHARP_TLBTOPAS_OPTS) -A"_TLB" -P+ -R- "$(SET_TLBOBJNAME)"
#
JSHARP_TLB_OPTS = $(LOCAL_TLB_OPTS)
JSHARP_TLB_COMMAND = "$(JSHARP_TLB_COMPILER)" /nologo $(JSHARP_TLB_OPTS) /out:"$(SET_TLBOBJNAME)" "$(SET_OBJNAME)"
#
JSHARP_RESOURCE_OPTS = $(LOCAL_RESOURCE_OPTS) /compile
JSHARP_RESOURCE_COMMAND = "$(JSHARP_RESOURCE_COMPILER)" $(JSHARP_RESOURCE_OPTS)
#
JSHARP_VJ_OPTS =  $(JSHARP_TARGET) $(JSHARP_PLATFORM) $(JSHARP_WARNING:-"") $(LOCAL_JSHARP_FLAGS) $(LOCAL_JSHARPFLAGS) $(JSHARP_STDLIBS) $(JSHARP_DEBUG)
JSHARP_COMMAND = "$(JSHARP_COMPILEUR)" /nologo $(JSHARP_VJ_OPTS) $(JSHARP_LIBPATH) /out:"$(SET_OBJNAME)" $(JSHARP_REFLIBS) 
#
JSHARP_POLICY_OPTS = $(LOCAL_POLICY_FLAGS)
JSHARP_POLICY_COMMAND = "$(JSHARP_POLICY_COMPILER)" /nologo $(JSHARP_POLICY_OPTS)
#
# SET_OBJNAME, SET_TLBOBJNAME
#
JSHARP_OPTS = $(JSHARP_TLBTOPAS_OPTS) $(JSHARP_TLB_OPTS)\
		$(JSHARP_RESOURCE_OPTS) $(JSHARP_VJ_OPTS) $(JSHARP_POLICY_OPTS)
#
_SIGN_OBJNAME = $(SET_OBJNAME)
_SIGN_ACTIVATION = $(SIGN_ACTIVATION) $(MKMK_DISABLE_SIGNTOOL)
#
DGM_VERSION = 1.2
DGM_DEPEND = _SIGN_ACTIVATION MKSIGNMS_OPTS
#
MKMK_DGM_BEHAVIOUR=update
#
SCRIPT_COMMAND = JSHARP_RESOURCE_COMMAND JSHARP_COMMAND JSHARP_TLB_COMMAND JSHARP_TLBTOPAS_COMMAND\
	[1] [2] JSHARP_POLICY_COMMAND MKSIGNMS_COMMAND
#
