#
# Specifications for Build step mkBSPython
#
METACLASS_NAME = CompilPython
METACLASS_SOURCE = pythonbuild
#
DGM_GRAPH_PATH = MODDGM_GRAPHPATH
#
SOURCE_EXTENSION = *.py
PYC_EXTENSION = .pyc
DGM_DEPEND = AR_OPTS BUILT_TYPE
#
#DGM_DEPEND =  METACLASS_NAME #PYC_PRESERVE_STRUCTURE LOCAL_PYCFLAGS PYC_COPY_SOURCE zzz
#DGM_VERSION = 0.1
#
