#
# Specifications for Build step mkBSCORBALnkShl2ndC
#
CORBA_CLIENT_DEFINE = CLIENT
CORBA_SERVER_DEFINE = SERVER
CORBA_CS_DEFAULT =
CORBA_CS = $(CORBA_JAVA_CS:-CORBA_CS_DEFAULT)
#
include mkBSLnkCommonDecl.mk
#
LD_OBJLIST = MODmkobjlist_C
#
LD_OPTS = /DLL $(LOCAL_OPTS) $(_MK_COMMON_OPTS) $(MACHINE_FLAG) /MANIFEST
#
CORBA_LIBS = Wsock32.lib
CORBA_LIBPATH = /LIBPATH:"$(CorbaCppBuildROOT_PATH)\lib"
#
LD_LIBS = $(CorbaCppBuildROOT_PATH:+CORBA_LIBS) $(LOCAL_LIBS) $(WS_LIBS) $(_MK_COMMON_LIBS)
LD_LIBPATH = $(CorbaCppBuildROOT_PATH:+CORBA_LIBPATH) $(LOCAL_LIBPATH) $(WS_LIBPATH) $(_MK_COMMON_LIBPATH)
# ~1
LD_COMMAND = "$(LD)" $(LD_OPTS) $(_MK_MANIFESTFILE_OPTS) $(LD_LIBPATH) $(LD_LIBS) @"$(LD_OBJLIST)" /OUT:
#
DGM_VERSION = 1.0
# ~3
MANIFEST_COMMAND = "$(MT_COMPILER)" -nologo -manifest "$(_MK_MANIFESTFILE)"%MANIFEST_OBJECTS% -outputresource:"$(RUNTIME_NAME);2"
EXTRA_COMMAND = $(MANIFEST_COMMAND)
#
DGM_DEPEND = _SIGN_ACTIVATION
_SIGN_ACTIVATION = $(SIGN_ACTIVATION) $(MKMK_DISABLE_SIGNTOOL)
#
#SCRIPT_COMMAND = LD_COMMAND [1] MANIFEST_COMMAND LD_SIGN_COMMAND
# ~2 = CAAV5Licensing
SCRIPT_COMMAND = ~1 ~2 ~3
#
