TODOVERSIONINFO=$(MkmkVERSIONINFO:@"STAGE")

LISTOF_VI_=_VI_COMPANYNAME _VI_LEGALCOPYRIGHT _VI_FILEDESCRIPTION _VI_ORIGINALFILENAME _VI_INCLUDE _VI_PRODUCTNAME _VI_STAGE

_VI_COMPANYNAME=$(FWCOMPANYNAME)
_VI_LEGALCOPYRIGHT=$(FWCOPYRIGHT)
_VI_FILEDESCRIPTION=$(DESCRIPTION:-FWNAME)
_VI_ORIGINALFILENAME=$(RTNAME)
_VI_INCLUDE=$(INCLUDENAME)
_VI_PRODUCTNAME=$(FWCOMPANYNAME)
_VI_STAGE=$(TODOVERSIONINFO)

LISTOF_VIH_=_VIH_MAJORVERSION _VIH_MINORVERSION _VIH_SERVICEPACK _VIH_BUILDNUMBER _VIH_STAGE

_VIH_MAJORVERSION=$(MAJORVERSION)
_VIH_MINORVERSION=$(MINORVERSION)
_VIH_SERVICEPACK=$(SERVICEPACK)
_VIH_BUILDNUMBER=$(BUILDNUMBER)
_VIH_STAGE=$(TODOVERSIONINFO)

#
DGM_VERSION = 1.0
#

