#
# Specifications for Build step PreCompilCORBAjavaS
#
CORBA_CLIENT_DEFINE = CLIENT
CORBA_SERVER_DEFINE = SERVER
#CORBA_CS_DEFAULT = $(CORBA_CLIENT_DEFINE) $(CORBA_SERVER_DEFINE)
CORBA_CS_DEFAULT = 
CORBA_CS = $(CORBA_JAVA_CS:-CORBA_CS_DEFAULT)
CORBA_OPTS = $(CORBA_JAVA_OPTS:-"")
CORBA_HOME = $(CorbaJavaROOT_PATH:-"")
CORBA_PATH = $(CORBA_HOME)\bin
CORBA_CONFIG = $(CORBA_HOME)\config
CORBA_COMPILER = $(CORBA_PATH)\idlj
CORBA_FILTER = $(CORBA_JAVA_FILTER:-"")
CORBA_JAVA_PACKAGE_CS = $(CORBA_JAVA_PACKAGE:-"com.dassault_systemes")
CORBA_PACKAGE = $(CORBA_JAVA_PACKAGE_S:-CORBA_JAVA_PACKAGE_CS)
CORBA_MANDATORY_OPTS = %CORBA_INCLUDE% -jP $(CORBA_PACKAGE)
CORBA_COMMAND = $(CORBA_COMPILER) $(CORBA_OPTS) $(CORBA_MANDATORY_OPTS) -jO "%TEMP_OBJECT_PATH%"
_TEMPORARYEXTENSION=.tmpjava_S
#
DGM_VERSION = 1.0
#

