#
# Specifications for Build step mkBSVB
#
METACLASS_NAME = CompilSharp
METACLASS_SOURCE = GrammarVI
#
DGM_GRAPH_PATH = MODDGM_GRAPHPATH
#
SOURCE_EXTENSION = *.vb
SOURCE_EXTENSION_SNK = *.snk
#
SOURCE_EXTENSION_XML = *.ProfileCard.xml $(MKMK_DEVSTAGE:%+"*.ProfileCard.dev")
SOURCE_EXTENSION_XML_REPLACEMENT = $(MKMK_DEVSTAGE:%+".dev .xml")
#
TLBTOPAS_EXTENSION = _TLB.pas
RESOURCE_FILTERS = "*.resx"
ASSEMBLYINFO_FILTERS = "*.h.vb"
#
DEPENDENT_ON = $(MOD_LinkWith) $(CLR_TLB) $(CLR_TLBTOPAS) $(VB_LIBPATH) $(VB_REFLIBS)
#
OBJLIST = .mkObjList
#
