#
# Specifications for Build step mkBSPostCompilCORBAjavaS
#
CORBA_CLIENT_DEFINE = CLIENT
CORBA_SERVER_DEFINE = SERVER
#CORBA_CS_DEFAULT = $(CORBA_CLIENT_DEFINE) $(CORBA_SERVER_DEFINE)
CORBA_CS_DEFAULT = 
CORBA_CS = $(CORBA_JAVA_CS:-CORBA_CS_DEFAULT)
CORBA_DEBUG = $(CORBA_JAVA_DEBUG:?"YES")
_TEMPORARYEXTENSION=.tmpjava_S
#
DGM_VERSION = 1.0
#

