# @(#) preprocess
# ----------------------
# Specifications for Build step mkBSCSharp
# ----------------------
include mkBSCompilersPathDecl.mk
include mkBSSignToolDecl.mk
# ----------------------
#if (defined MK_BITMODE) && (MK_BITMODE == 64)
#rem: 64-bit mode
CSHARP_PLATFORM = /platform:x64
#endif
# ---------------------
TODOXMLASSEMBLYANDVERSIONINFOANDPOLICY=$(MkmkXMLASSEMBLYANDVERSIONINFOANDPOLICY:@"YES")
# ---------------------
CSHARP_TLBTOPAS_COMPILER = $(_MK_TLIBIMP_UTILPATH)
CSHARP_TLB_COMPILER = $(_MK_TLBEXP_UTILPATH)
CSHARP_RESOURCE_COMPILER = $(_MK_RESGEN_UTILPATH)
CSHARP_COMPILEUR = $(_MK_CSC_UTILPATH)
CSHARP_TLBTOASSEMBLY_COMPILER = $(_MK_TLBIMP_UTILPATH)
CSHARP_ASSEMBLYTOIL_COMPILER = $(_MK_ILDASM_UTILPATH)
CSHARP_ILTOASSEMBLY_COMPILER = $(_MK_ILASM_UTILPATH)
CSHARP_POLICY_COMPILER = $(_MK_AL_UTILPATH)
# ---------------------
CSHARP_CONSOLE = /target:exe
CSHARP_WINDOWS = $(DISABLE_CONSOLE:?"/target:winexe")
CSHARP_DLL = /target:library
CSHARP_EXE_TYPE = $(CSHARP_WINDOWS:-CSHARP_CONSOLE)
CSHARP_EXE = $(CLR_EXE_TYPE:%+CSHARP_EXE_TYPE)
CSHARP_TARGET= $(CSHARP_EXE:-CSHARP_DLL)
CSHARP_ILTOASSEMBLY_DLL = /dll
CSHARP_ILTOASSEMBLY_EXE = $(CLR_EXE_TYPE:%+"/exe")
CSHARP_ILTOASSEMBLY_TARGET = $(CSHARP_ILTOASSEMBLY_EXE:-CSHARP_ILTOASSEMBLY_DLL)
#
CSHARP_WARNING = $(MKMK_WARNING:%-"/w:0")
CSHARP_DEBUG = $(MKMK_DEBUG:+"/debug+")
#
#CSHARP_STDLIBSPATH ="/lib:$(MkmkMSVCSHARPDIR)"
CSHARP_J2CLIBS = /r:"vjslib.dll" /r:"$(MkmkROOTINSTALL_PATH)\code\clr\enojava2csext.dll"
CSHARP_STDLIBS = $(_MKMK_JAVA2CSHARP:+CSHARP_J2CLIBS) /r:"System.DirectoryServices.dll" /r:"System.Data.dll" /r:"System.XML.dll" /r:"System.EnterpriseServices.dll" /r:"System.Drawing.dll" /r:"System.Web.dll"
#
CSHARP_TLBTOPAS_OPTS = $(LOCAL_TLBTOPAS_FLAGS)
CSHARP_TLBTOPAS_COMMAND = "$(CSHARP_TLBTOPAS_COMPILER)" $(CSHARP_TLBTOPAS_OPTS) -A"_TLB" -P+ -R- "$(SET_TLBOBJNAME)"
#
CSHARP_TLB_OPTS = $(LOCAL_TLB_OPTS)
CSHARP_TLB_COMMAND = "$(CSHARP_TLB_COMPILER)" /nologo $(CSHARP_TLB_OPTS) /out:"$(SET_TLBOBJNAME)" "$(SET_OBJNAME)"
#
CSHARP_RESOURCE_OPTS = $(LOCAL_RESOURCE_OPTS) /compile
CSHARP_RESOURCE_COMMAND = "$(CSHARP_RESOURCE_COMPILER)" $(CSHARP_RESOURCE_OPTS)
#
CSHARP_CS_OPTS = $(CSHARP_TARGET) $(CSHARP_PLATFORM) $(CSHARP_WARNING:-"") $(LOCAL_CSHARP_FLAGS) $(LOCAL_CSHARPFLAGS) $(CSHARP_STDLIBS) $(CSHARP_DEBUG)
CSHARP_COMMAND = "$(CSHARP_COMPILEUR)" /nologo $(CSHARP_CS_OPTS) $(CSHARP_LIBPATH) /out:"$(SET_OBJNAME)" $(CSHARP_REFLIBS)
#
CSHARP_TLBTOASSEMBLY_OPTS = $(LOCAL_TLBTOASSEMBLY_FLAGS) $(LOCAL_TLBTOASSEMBLYFLAGS) /strictref
CSHARP_TLBTOASSEMBLY_COMMAND = "$(CSHARP_TLBTOASSEMBLY_COMPILER)" /nologo $(CSHARP_TLBTOASSEMBLY_OPTS) /namespace:"$(SET_NAMESPACE)" /out:"$(SET_OBJNAME)"
#
CSHARP_ASSEMBLYTOIL_OPTS = $(LOCAL_ASSEMBLYTOIL_FLAGS)
CSHARP_ASSEMBLYTOIL_COMMAND = "$(CSHARP_ASSEMBLYTOIL_COMPILER)" /nobar $(CSHARP_ASSEMBLYTOIL_OPTS) /out="$(OBJPATH)\$(SET_NAMESPACE).il" "$(SET_OBJNAME)" 
#
CSHARP_ILTOASSEMBLY_OPTS = $(LOCAL_ILTOASSEMBLY_FLAGS)
CSHARP_ILTOASSEMBLY_COMMAND = "$(CSHARP_ILTOASSEMBLY_COMPILER)" /nologo /quiet $(CSHARP_ILTOASSEMBLY_OPTS) $(CSHARP_ILTOASSEMBLY_TARGET) "$(OBJPATH)\$(SET_NAMESPACE).il" /output="$(SET_OBJNAME)"
#
CSHARP_POLICY_OPTS = $(LOCAL_POLICY_FLAGS)
CSHARP_POLICY_COMMAND = "$(CSHARP_POLICY_COMPILER)" /nologo $(CSHARP_POLICY_OPTS)
#
# SET_OBJNAME, SET_TLBOBJNAME, SET_NAMESPACE
#
CSHARP_OPTS = $(CSHARP_TLBTOPAS_OPTS) $(CSHARP_TLB_OPTS)\
		$(CSHARP_RESOURCE_OPTS) $(CSHARP_CS_OPTS) $(CSHARP_TLBTOASSEMBLY_OPTS)\
		$(CSHARP_ASSEMBLYTOIL_OPTS) $(CSHARP_ILTOASSEMBLY_OPTS) $(CSHARP_POLICY_OPTS)
#
_SIGN_OBJNAME = $(SET_OBJNAME)
_SIGN_ACTIVATION = $(SIGN_ACTIVATION) $(MKMK_DISABLE_SIGNTOOL)
#
DGM_VERSION = 1.2
DGM_DEPEND = _SIGN_ACTIVATION MKSIGNMS_OPTS
#
SCRIPT_COMMAND = CSHARP_RESOURCE_COMMAND CSHARP_COMMAND CSHARP_TLB_COMMAND CSHARP_TLBTOPAS_COMMAND\
	[1] [2] CSHARP_POLICY_COMMAND MKSIGNMS_COMMAND
#
