#
# Specifications for Build step mkBSCompil
#
METACLASS_NAME = XRef-Database
#
SOURCE_EXTENSION_FOR_TEST = *.mkDG 
#
DGM_GRAPH_PATH = XREFDGM_GRAPHPATH
#
XREFDB_GRAPHS = MODDGM_GRAPHPATH MODDGM_GRAPHPATH_JAVA MODDGM_GRAPHPATH_DOC 
#
