#
# Specifications for Build step mkBSCabJar
#
METACLASS_NAME = Archive
#
DGM_GRAPH_PATH = MODDGM_GRAPHPATH
#
CABJAR_SRCMAC = INCLUDE_SRC
CABJAR_RESMAC = INCLUDE_RESOURCE
CABJAR_PLUGMAC = PLUGIN_OPTIONS

CABJAR_NLSFILETREE = WSNLSFileTree
CABJAR_PKGFILETREE = WSPKGFileTree

CABJAR_PLUGDEF = PLUGIN_DEFINITION
CABJAR_PLUGSKE = PLUGIN_SKELETON
CABJAR_PLUGSCH = PLUGIN_SCHEMA
CABJAR_PLUGNLS = PLUGIN_NLS

CABJAR_OSXPKG = PLUGIN_PKGINDEX
#
