#
# Java versions (JAVA_PATH and JAVA_OPTS)
#
1.3_OPTS = -source 1.3 -target 1.3
JAVA_DEPRECATED_OPTION = -deprecation
#
1.6_PATH = $(Java6ROOT_PATH)
1.6_OPTS = $(JAVA_DEPRECATED_OPTION) $(MKMK_TOOLSEMBEDDED:%-1.3_OPTS)
#
JAVA_VERSION_DEFAULT = 1.6
#
