<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 ABC - Application Builder Configuration
M7 1 2
M6 1 2553
M2 1 MAB.prd
M3 2 MAB.prd,2
EOF
X1m0IACIfyiRdqAi1nyQcKMyxzoGHROoridN8K4EwyC60bXtINKpDK8evZK5EyujxvgcGN6Lne8lMa+HCXDGizYmwcyH1GKt6W8zpzu8M9F5a74ozqLtMFmlpW6Q+05cYjdD+/ud5lzo4cjzflz6mwUOWhEAv4VyMBlglLSDA+IVakaOA/Eq8TCvQMSdE5ymdXGHw9abInxptp/7Y+TXrvefqLLHPzc1CtwcARdx2LGhXG8UMrShQ5oIZi/PKmViEd3VZAMXEPYvs75O3jYj1rjZEUyrtX7qJBP9mV80psKNxlaxPV19z6L+ps/qd5eBBu7Phb3YMFRLCAZg6ExFlQ==
