<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 ALR - CAA - All-in-One RADE Configuration
M7 1 2
M6 1 2636
M2 1 DMC.prd
M3 2 DMC.prd,2
M2 1 MAB.prd
M3 2 MAB.prd,2
M2 1 CID.prd
M3 2 CID.prd,2
M2 1 JID.prd
M3 2 JID.prd,2
M2 1 CUT.prd
M3 2 CUT.prd,2
M2 1 JUT.prd
M3 2 JUT.prd,2
M2 1 CSC.prd
M3 2 CSC.prd,2
M2 1 SCM.prd
M3 2 SCM.prd,2
M2 1 CDG.prd
M3 2 CDG.prd,2
M2 1 WAC.prd
M3 2 WAC.prd,2
M2 1 ITC.prd
M3 2 ITC.prd,2
M2 1 IDD.prd
M3 2 IDD.prd,2
EOF
a29AR/nDWCXFb8suXznLydLSfKUmkVky/YkB15ogJc4xdhcXQrrd816M9jV//cnfVfsWIz8vRI9NHuwBXsZg3flAAbHpUMn3xO38M/8hhwNIVXB8tbrsADgqDkMDGf9UMRpq1Uh48OnwwcFo0Japw8lTo4Sw5VzNVCKq4fUJHbnXtf7f0pfmT/wzAoDF0KaWM6vjiImUPQPINEDx2pbVnEpd/Xi4kCFpKokCBjlmD1MbhaWQJnInPnmT7mlKo/blJ45Xh2m5iIgly2B7UIxSXQTMZyEcZ8kgrcd6MEA2Y3BvZOL/5zkClKuplfVpjukqYJYMrvGu5R4AL7ijq15EXw==
