<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 CDV - CAA - C++ Base Development Configuration
M7 1 2
M6 1 2494
M2 1 MAB.prd
M3 2 MAB.prd,2
M2 1 CID.prd
M3 2 CID.prd,2
EOF
ITmmHNFt5HoSu0xJ++yBlX85LyTjiGzEf8kW4YpSet/MMajRWeR55puQlFpPrnn4w7sQI7o097bo9lDRwI3uWTGLdOvSbp3LgDZfK3tMN3XNknGXDvglMh3Zo7z0C21MJ784tRbrMvfDotAI6atr0fIPC7VsJydKAGs+7NqTYZjUo/PYa4hUPRnqjWZDqoD18Cg5b4vChBOm0gSTwSktSV1t+tl5knlOlWKc65U8yDfroY0ZcEx0zlkkft0yiAAWJazp/uAru1GBSdebgvQTJSJuwvj8EoRTdAIheSDpXPgGVftDwY12kk9/jrhJ5/kqycFwoT2ivq149ROR6Yz83Q==
