<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 IDD - CAA - Interactive Dialog Designer Product
M6 1 3425
M7 1 2
M9 1 Addon
M2 1 DSxDevVisualDesigner
M3 2 DSxDevVisualDesigner,2
M1 1 CID.prd
EOF
GbsixLPu5dTsE9eW/8axfZhEhEt6cfdinbZc9K/kkVHup0PwM/IhGUcYDDYiDw+Nmf0Rtt/IOq4Stw5Yy7JgFgtXEP8RqDXQj8q6RZcN6Td0Mu4cf11aDPJw3T/N6vh4D3T4YEzskdYeBJ9RLyfwBHxCIx+QIaeeIVMJq/yMfJQI+ZU+DIaclxc9IuJHI9LRW9f9cQh1QlPVw3OOHE0zJgeCyCq3fQGgvMG4NrLQ3yZdMx/ieLYhUEK4xvsQPgewcoNfgj6yACKCfKQ/4Vv99zXvOoiHPJI5Qq4P2F2rZGVUwZLahfT2X/Utzax3K2SuQ0qNB8CkPAJdULCb3zS9bA==
