<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 PAD - CAA - Enterprise Portal Application Design Configuration
M7 1 2
M6 1 2738
M2 1 MAB.prd
M3 2 MAB.prd,2
M2 1 DMC.prd
M3 2 DMC.prd,2
M2 1 WAC.prd
M3 2 WAC.prd,2
EOF
SvkG0V58pvcW63HNJTnbB55CgMQ8IQIhi4tluRoczCqVieROkzN0kvl0B7xkNlKe0HL0mgZYzzi6cSSgh44uP2ymwTQWXE18ynAW5Xp1mWy45B4aRKNL/LGY4pnjpxVuiRwK0xcjRvnjxq9dfoXavSbSGez9aff5/wxo62moOq+MvXsw5oot+ZjNO0iNkSTiLreGDo/JrvvP9l9xm3264f3GJNJzNuY33Npf+BOXJwM5oqtF+PNGbFjB2jzHUYwYzsT54iQAcz8g/tC8RCHjIt2A9Y8w9hvKy/NCLZwzT1Oh/qZeGkQQ6NI1E1ZOr3Y67PYL236zmUP0vPL3kee31w==
