/* XPM */
static char * ColpsExp_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 3 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor3	m black	c red",
"X	s iconColor1	m black	c black",
/* pixels */
"                                ",
"   ....       ....       ....   ",
"  ......     ......     ......  ",
" ........   ........   ........ ",
" ........   ........   ........ ",
" ........   ........   ........ ",
" ........   ........   ........ ",
"  ......     ......     ......  ",
"   ....       ....       ....   ",
"                              XX",
"                           XXXXX",
"                        XXXXXX  ",
"                      XXXXX     ",
"                   XXXXX        ",
"                XXXXXX          ",
"             XXXXXX             ",
"          XXXXXX                ",
"        XXXXX                   ",
"     XXXXX                      ",
"  XXXXXX                        ",
"XXXXX                           ",
"XX                              ",
".......   ..     ..   ........  ",
".......    ..   ..    ........  ",
"..          .. ..     ..    ..  ",
"..           ...      ..    ..  ",
".....        ...      ........  ",
".....       .. ..     ........  ",
"..         ..   ..    ..        ",
".......   ..     ..   ..        ",
".......  ..       ..  ..        ",
"                                "};
