/* XPM */
static char * LeftFile_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 3 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor4	m white	c green",
"X	s iconColor6	m white	c yellow",
/* pixels */
"   ...  .         XX            ",
" . .... ..   ..   XX            ",
" ..   .  .   ...  XX            ",
"..    .  .  ..    XX            ",
"       .  ...     XX            ",
"   .            . XX            ",
" .....  .     ..  XX            ",
"    ... ..  ...   XX            ",
"      .. .....   .XX            ",
"           .    ..XX            ",
"  ....  .     ... XX            ",
" ..   .  . . ..   XX            ",
"      .. .....    XX            ",
"      .  .     .. XX            ",
" ...  .  .     .. XX            ",
"   ......... .  . XX            ",
"                  XX            ",
"              ..  XX            ",
"       .  . .  .. XX            ",
"  ....  .         XX            ",
"  .               XX            ",
"                  XX            ",
"   .              XX            ",
" ..... .. .   ... XX            ",
"    .........     XX            ",
"                  XX            ",
"    ..  .         XX            ",
"   ...  .       ..XX            ",
"..  ....... .  .. XX            ",
".      .  .. ...  XX            ",
"             ..   XX            ",
"                  XX            "};
