/* XPM */
static char * LeftpRight_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 3 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor6	m white	c yellow",
"X	s iconColor4	m white	c green",
/* pixels */
"              ..                ",
"              ..                ",
"   X XX X     ..                ",
"XX    XXXXXXX ..                ",
"         XX   ..                ",
"              ..                ",
"              ..        XXX     ",
"              ..      X   XXX   ",
"              .. XX X       XX  ",
"              ..XX           X  ",
"              ..             XX ",
"              ..                ",
"              ..                ",
"           X  ..                ",
"   X  XXX XXX ..                ",
" XXXXXXXX   X ..                ",
" X          X ..                ",
"              ..                ",
"              ..                ",
"              ..    XX    XX    ",
"              ..  X  XX X XX  XX",
"              .. X         XX  X",
"              ..                ",
"              ..                ",
"              ..                ",
"              ..                ",
"              ..                ",
"              ..                ",
"  XXX      XX ..                ",
"XXX XXXXX     ..                ",
"              ..                ",
"              ..                "};
