/* XPM */
static char * NextUnresolved_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 4 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray5	m black	c #737373737373",
"X	s iconColor2	m white	c white",
"o	s iconColor1	m black	c black",
/* pixels */
"                ................",
"                ................",
"                .XXXXXXXXX..XXXX",
"                .XXXXXXXXX..XXXX",
"  oooooooooooo  .XooXoXoXX..XXXo",
"  oooooooooooo  .XXXXooXoX..XoXo",
"  oooooooooooo  .XoooXXXXX..XXXX",
"  ooo           .XXXXXooXX..XXXX",
"  ooo           .XoXoXXoXX..XXXo",
"  ooo           .XXXXXXXXX..XXXX",
"  ooo           .XXXXXXXXX..XXXX",
"  ooo           ................",
"  ooo    o      ................",
"  ooo    oo     .XXXXXXXXXXXXXXX",
"  ooo    ooo    .XXoXoXXoXXoXXXo",
"  ooo    oooo   .XoXXoooXoXoXoXo",
"  oooooooooooo  .XXXXXXXXXXXooXX",
"  ooooooooooooo .XoXXoooooXoXXoX",
"  oooooooooooo  .XXXXXoXXXXXXXXX",
"         oooo   .XoXXoooXoooXXoo",
"         ooo    .XXXXXXXXXXXXXXX",
"         oo     ................",
"         o      ................",
"                .XXXXXXXX..XXXXX",
"                .XXoXoooX..XooXo",
"                .XoXooXXX..XXoXo",
"                .XXXXXXoX..XoXXX",
"                .XXoXXooX..Xoooo",
"                .XXXXXXXX..XXXXX",
"                .XXXXXXXX..XXXXX",
"                ................",
"                ................"};
