/* XPM */
static char * NextUnresolved_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 4 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray5	m black	c #737373737373",
"X	s iconColor2	m white	c white",
"o	s iconColor1	m black	c black",
/* pixels */
"         o      ................",
"         oo     ................",
"         ooo    .XXXXXXXX..XXXXX",
"         oooo   .XXoXoooX..XooXo",
"  oooooooooooo  .XoXooXXX..XXoXo",
"  ooooooooooooo .XXXXXXoX..XoXXX",
"  oooooooooooo  .XXoXXooX..Xoooo",
"  ooo    oooo   .XXXXXXXX..XXXXX",
"  ooo    ooo    .XXXXXXXX..XXXXX",
"  ooo    oo     ................",
"  ooo    o      ................",
"  ooo           .XXXXXXXXXXXXXXX",
"  ooo           .XXoXoXXoXXoXXXo",
"  ooo           .XoXXoooXoXoXoXo",
"  ooo           .XXXXXXXXXXXooXX",
"  ooo           .XoXXoooooXoXXoX",
"  ooo           .XXXXXoXXXXXXXXX",
"  ooo           .XoXXoooXoooXXoo",
"  ooo           .XXXXXXXXXXXXXXX",
"  ooo           ................",
"  ooo           ................",
"  ooo           .XXXXXXXXX..XXXX",
"  ooo           .XXXXXXXXX..XXXX",
"  ooo           .XXXXXooXX..XXXX",
"  ooo           .XXXXXXXXX..XXXX",
"  oooooooooooo  .XooXoXoXX..XXXo",
"  oooooooooooo  .XXXXooXoX..XoXo",
"  oooooooooooo  .XoooXXXXX..XXXX",
"                .XoXoXXoXX..XXXo",
"                .XXXXXXXXX..XXXX",
"                ................",
"                ................"};
