/* XPM */
static char * Recommand_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 3 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor4	m white	c green",
"X	s iconColor1	m black	c black",
/* pixels */
"                                ",
"............................... ",
"............................... ",
"............................... ",
"                                ",
"                                ",
"............................... ",
"............................... ",
"............................... ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"XXXXXXXXXXXXXX   XXXXXXXXXXXXXX ",
"XXXXXXXXXXXXXX   XXXXXXXXXXXXXX ",
"XXXXXXXXXXXXXX   XXXXXXXXXXXXXX ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"............................... ",
"............................... ",
"............................... ",
"                                ",
"                                ",
"                                "};
