/* XPM */
static char * Reset_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 7 1 0 0",
/* colors */
" 	s iconGray3	m white	c #adadadadadad",
".	c #AF00AF00AF00",
"X	c #180010005200",
"o	s iconColor1	m black	c black",
"O	c #3F0071009900",
"+	s iconColor2	m white	c white",
"@	c #39009C00A500",
/* pixels */
"................................",
".....XoO........................",
"....XoO.......++++++............",
"....oO......+++++oooooo.........",
"...XO.....+++++oo@@@@@@oo.......",
"..XXO.....+++oo@@XXXXXX@@oo.....",
".XXo....+++o@XXXXXXXXXXXXXX@o...",
"XXXo....++o@XXXXXXXXXXXXXXXX@o..",
"XXoO...+++o@XXXX+++++++XXXXXX@o.",
"XXoO...++oXXXX++ooooo++++XXXXX@o",
"X+oO...++oXXXX+oOOOOOo++++XXXX@o",
"X+oO...++oXXX++O.....Ooo+++XXXX@",
"X+oO...++oXXX+o.......OO+++XXXXX",
"X++o...++oXXXXo..+++....Oo++XXXX",
"X++o....++@XXXo.ooo++...Oo+++XXX",
"X++o....++oOOOO@@@@o++...Oo++XXX",
"XX++O.....+++..oXXXXo++..Oo++XXX",
"XX++oO.........o+XXXo++...Oo+XXX",
"XXX++oOO.......o+XXXo++...Oo+XXX",
"XXXX++++oOOOOOo+XXXXo++...Oo+XXX",
"XXXX+++++ooooo++XXXXo++...OoXXXX",
"@XXXX++++++++++XXXX@+++...OoXXX.",
"o@XXXXXXXXXXXXXXXX@o++...OoXXXX.",
".o@XXXXXXXXXXXXXX@o+++...OoXXX..",
"..o@XXXXXXXXXXX@@o+++....OoXXX..",
"...o@@@XXXXXX@@oo+++....OoXXX...",
"....ooo@@@@@@oo+++++....OoXXX...",
".......oooooo+++++......oXXX....",
"..........++++++.......OXXX.....",
".....................OOoXX......",
"....................OooX........",
"................................"};
