/* XPM */
static char * Reset_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 7 1 0 0",
/* colors */
" 	s iconGray3	m white	c #adadadadadad",
".	c #AF00AF00AF00",
"X	c #180010005200",
"o	s iconColor1	m black	c black",
"O	c #3F0071009900",
"+	s iconColor2	m white	c white",
"@	c #39009C00A500",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"    ........................................    ",
"    .........Xoo............................    ",
"    ........XoO.............................    ",
"    .......XoO........++++++++..............    ",
"    ......XoO.......++++++ooooooo...........    ",
"    .....XoO......+++++ooo@@@@@@@ooo........    ",
"    ....XXoO.....++++oo@@@XXXXXXX@@@oo......    ",
"    ...XXoO.....++++o@@XXXXXXXXXXXXX@@o.....    ",
"    ...XXoO....++++o@XXXXXXXXXXXXXXXXX@o....    ",
"    ..XXXoO....+++o@XXXXXXXXXXXXXXXXXXX@o...    ",
"    ..XXoO....++++o@XXXXX++++++++XXXXXXX@o..    ",
"    ..XXoO....+++o@XXXX++++++++++++XXXXX@o..    ",
"    .XXXoO....++o@XXXX+++oooooo+++++XXXXX@o.    ",
"    .XX+oO....++o@XXXX++oOOOOOOo+++++XXXX@o.    ",
"    .XX+oO....++o@XXX++oO......Ooo++++XXXX@o    ",
"    XXX+oO....++o@XXX+oO........OOo+++XXXXXo    ",
"    XXX+oO....++o@XXX+oO..........Oo+++XXXXo    ",
"    XXX++oO...++o@XXXXoO..+++......Oo++XXXXX    ",
"    XXX++oO....++o@XXXoO.ooo+++....Oo+++XXXX    ",
"    XXX++oO....+++oOOOOo@@@@o+++....Oo++XXXX    ",
"    XXX+++oO....+++ooo.OoXXX@o++....Oo++XXXX    ",
"    XXXX++oO......+++..OoXXXX@o++...Oo++XXXX    ",
"    XXXX+++oO..........Oo+XXX@o++....Oo+XXX.    ",
"    @XXXX+++oOO........Oo+XXX@o++....Oo+XXX.    ",
"    @XXXX++++ooO......Oo++XXX@o++....Oo+XXX.    ",
"    o@XXXX+++++oOOOOOOo++XXXX@o++....Oo+XXX.    ",
"    o@XXXXX+++++oooooo+++XXXX@o++....OoXXXX.    ",
"    .o@XXXXX++++++++++++XXXX@o+++....OoXXX..    ",
"    .o@XXXXXXX++++++++XXXXX@o++++....OoXXX..    ",
"    ..o@XXXXXXXXXXXXXXXXXXX@o+++....OoXXXX..    ",
"    ...o@XXXXXXXXXXXXXXXXX@o++++....OoXXX...    ",
"    ....o@@XXXXXXXXXXXXX@@o++++.....OoXXX...    ",
"    .....oo@@@XXXXXXX@@@oo++++.....OoXXX....    ",
"    .......ooo@@@@@@@ooo+++++......OoXXX....    ",
"    ..........ooooooo++++++.......OoXXX.....    ",
"    .............++++++++........OoXXX......    ",
"    ...........................OOoXXX.......    ",
"    ..........................OooXX.........    ",
"    ........................oooXX...........    ",
"    ........................................    ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
