/* XPM */
static char * RightFile_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 3 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor6	m white	c yellow",
"X	s iconColor4	m white	c green",
/* pixels */
"           ..                   ",
"           ..                   ",
"           ..  XX        XX  X  ",
"           .. XXXX  X  XXXXXX   ",
"           ..     XXXXXXX       ",
"           ..                   ",
"           ..  XX   X  XX     X ",
"           .. XXXX       XXXX   ",
"           ..    XXX XX   XX    ",
"           ..                   ",
"           ..  X                ",
"           .. XXXXX XX XX X    X",
"           ..XX X XXXXXXXXXXXX  ",
"           ..      X  X X       ",
"           ..                   ",
"           ..    X              ",
"           ..   XXXXXXXXXXXX    ",
"           ..XX             X   ",
"           ..               XXX ",
"           ..     XXXXXX        ",
"           ..   XXX XX X        ",
"           ..  XX       X       ",
"           ..XXX  X  X  XX XXXX ",
"           ..    XX  X          ",
"           ..   XXXX XX         ",
"           ..  XX  X  X     X   ",
"           .. XX   XX XX    X   ",
"           ..       X  XXX      ",
"           ..  XX       XXX     ",
"           .. XXXXX  X   XX     ",
"           ..     X  X          ",
"           ..                   "};
