/* XPM */
static char * RightpLeft_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 3 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor6	m white	c yellow",
"X	s iconColor4	m white	c green",
/* pixels */
"              ..                ",
"              ..  XX            ",
"              .. X XX       XX  ",
"              .. X  XX      X   ",
"              ..     XX XXX     ",
"              ..      XX        ",
"              ..                ",
"              ..                ",
"        X XX  ..                ",
"      X     X ..                ",
" XX X       X ..                ",
"   XX         ..                ",
"              ..         X XX   ",
"              ..            XX  ",
"              ..   X  XX    XXX ",
"              .. XXXX         X ",
"              .. X            X ",
"              ..                ",
"              ..                ",
"              ..                ",
"              ..                ",
"  XX          ..                ",
" X  XXXXXXXXX ..                ",
"              ..                ",
"              ..                ",
"              ..                ",
"              ..       XXX      ",
"              ..  XXXX   XX     ",
"              .. XX X     XX XX ",
"              ..XX         XXX  ",
"              ..                ",
"              ..                "};
