/N3CERRPP
////////////
////////////  PARAMETER
////////////
N3C030001  4  Parameter &I03 is no number
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value of the &I03. parameter
&                     &C03
&             can not be transformed into a number!
/////////////////////////////////////////////////////////
N3C030002  4  Parameter is no integer
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value of the parameter
&                     &C03
&             is no integer!
/////////////////////////////////////////////////////////
N3C030003  4  Parameter &I03 is undefined
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value of the &I03. parameter
&                     &C03
&             is undefined!
/////////////////////////////////////////////////////////
N3C030004  4  Parameter &I03 is not allowed in this context
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value of the &I03. parameter
&                     &C03
&             is not allowed in this context!
/////////////////////////////////////////////////////////
N3C030005  5  Error in contour recalculation
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value of parameter &C03
&             is not allowed in this context!
/////////////////////////////////////////////////////////
N3C030006  4  Parameter &I03 exceeds its maximum value
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value of the &I03. parameter
&                     &F01(13.5)
&             exceeds its maximum value!
&                     &F02(13.5)
/////////////////////////////////////////////////////////
N3C030007  4  Parameter &I03 falls below its minimum value
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value of the &I03. parameter
&                     &F01(13.5)
&             falls below its minimum value!
&                     &F02(13.5)
/////////////////////////////////////////////////////////
N3C030008  4  Error while computing parameter &I03
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while computing parameter &I03
&                     &F01(13.5)
/////////////////////////////////////////////////////////
N3C030009  5  Error while formatting
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value &F01(13.5)
&             can not be formatted correspond to
&             Format: &C03
/////////////////////////////////////////////////////////
N3C030010  5  Error while formatting parameter &I03
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The value of the &I03. parameter
&                     &F01(13.5)
&             can not be formatted correspond to
&             format: &C03
/////////////////////////////////////////////////////////
N3C030011  4  Error while formatting line number
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while formatting the line number
&                     &I03
&             Format: &C03
/////////////////////////////////////////////////////////
N3C030012  5  Parameter &I03 w/o address character should be set
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Parameter &I03 w/o address character should be set
&                     &C03
/////////////////////////////////////////////////////////
N3C030013  5  Parameter &I03 w/o address character should be set
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Parameter &I03 w/o address character should be set
&                     &C03
&             When Turning the 3rd coordinate will be set
/////////////////////////////////////////////////////////
N3C030014  5  Invalid starting plane given
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Invalid starting plane given
&                     &C03
/////////////////////////////////////////////////////////
//////////
//////////    SYNTAX Error
//////////
/////////////////////////////////////////////////////////
N3C030015  4  APT Syntax Error: Not enough parameters
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Line must contain at least &I03 parameter!
/////////////////////////////////////////////////////////
N3C030016  4  APT Syntax Error: Quantity of parameter too large
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Line must contain at most &I03 parameter!
/////////////////////////////////////////////////////////
N3C030017  4  APT: general error in parameter
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error: Wrong number of parameters or
&             unknown parameters in APT-line!
/////////////////////////////////////////////////////////
N3C030018  5  APT: Check cycle definition
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error: Check cycle definition
/////////////////////////////////////////////////////////
N3C030019  5  APT: Check cycle definition
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error: Check cycle definition
&             Name of cycle         : &C03
/////////////////////////////////////////////////////////
N3C030020  5  APT: check cycle link-definition
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error: Check cycle link-definition
&             Name of cycle         : &C03
/////////////////////////////////////////////////////////
N3C030021  5  APT: Check cycle call
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error: Check cycle call
&             Name of cycle         : &C03
/////////////////////////////////////////////////////////
N3C030022  5  APT: Check cycle approaching formula
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error: Check cycle approaching formula
&             Name of cycle         : &C03
/////////////////////////////////////////////////////////
N3C030023  4  APT: No cycle call before end of program
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No cycle call follows this cycle definition
&             before end of program!
&             Name of cycle         : &C03
/////////////////////////////////////////////////////////
N3C030024  4  APT: No traverse movement after RAPID
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error: There is no traverse movement
&             after RAPID before end of program!
/////////////////////////////////////////////////////////
N3C030025  5  APT-line is not formatted as in configuration
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT-line is not formatted as in configuration
/////////////////////////////////////////////////////////
N3C030026  4  PPRINT missed after TOOLNO
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             PPRINT missed in command line following the TOOLNO command
/////////////////////////////////////////////////////////
N3C030027  5  Error special CUTCOM
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error in special CUTCOM (Deckel Dialog 4)
&             Call of correction missed, only CUTCOM/OFF programmed!
/////////////////////////////////////////////////////////
N3C030028  5  Error special CUTCOM
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             APT Syntax Error in special CUTCOM (Deckel Dialog 4)
&             APT-word CUTCOM/OFF expected before traversing movement!
/////////////////////////////////////////////////////////
N3C030029  5  CUTCOM/(LEFT!RIGHT) is not yet switched off!
&             Line number APT   : &I01
&             Line number Macro : &I02
&             APT-line          :
&             &C02
&             Subprogram        : &C01
&             CUTCOM/(LEFT!RIGHT) is not yet switched off!
/////////////////////////////////////////////////////////
N3C030030  5  No master defined at beginning of program!
&             Subprogram     : &C01
&             No master is defined at the beginning of the program!
/////////////////////////////////////////////////////////
N3C030031  5  &I03 Master defined at beginnig of program
&             Line number APT   : &I01
&             Line number Macro : &I02
&             APT-line          :
&             &C02
&             Subprogram        : &C01
&             &I03 master defined at the beginning of the program!
/////////////////////////////////////////////////////////
N3C030032  4  OPSKIP/ON was programmed twice!
&             Line number APT   : &I01
&             Line number Macro : &I02
&             APT-line          :
&             &C02
&             Subprogram        : &C01
&             OPSKIP/ON was programmed twice!
/////////////////////////////////////////////////////////
N3C030033  3  No traversing movenment after APT-word Macro
&             Line number APT   : &I01
&             APT-line          :
&             &C02
&             Subprogram        : &C01
&             No traversing movement is defined before end of
&             Macro-APT-/APT-file.
&             Macro can not access on coordinates.
/////////////////////////////////////////////////////////
N3C030034  4  Error in description of format
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Macro-line            :
&             &C03
&             Subprogram            : &C01
&             Error in description of format in the macro-definition
&                     &&C04
/////////////////////////////////////////////////////////
//////////
//////////    OUTPUT Error
//////////
/////////////////////////////////////////////////////////
N3C030035  4  Error while output of NC-block
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while output of NC-block
&             Name / type of block  : &C03
/////////////////////////////////////////////////////////
N3C030036  4  Error while output of NC-block
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while replacing * variables in output of NC-block
&             Name / type of block  : &C03
&             line                  : &C04
/////////////////////////////////////////////////////////
N3C030037  4  Wrong entry in NC command line
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Wrong entry in NC command line
&             Name of block: &C03
/////////////////////////////////////////////////////////
N3C030038  4  Tabulator of line number too large
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Tabulator of line number too large
/////////////////////////////////////////////////////////
N3C030039  4  Tabulator too large
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Tabulator too large
/////////////////////////////////////////////////////////
N3C030040  4  Wrong starting value for line number
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Starting value of line number is wrong or undefined
&             Name of block: &C03
/////////////////////////////////////////////////////////
N3C030041  4  Wrong starting value of line number
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Starting value of line number wrong or undefined
/////////////////////////////////////////////////////////
N3C030042  3  Line number exceeds maximum
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Line number exceeds maximum
/////////////////////////////////////////////////////////
N3C030043  4  Tabulator-position already used
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Tabulator-position already used
/////////////////////////////////////////////////////////
N3C030044  4  Element does not match with line
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Element does not match with line
/////////////////////////////////////////////////////////
N3C030045  4  String too long
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in routine TXTIN: String is too long
&             Name of block         :
&             &C03
/////////////////////////////////////////////////////////
N3C030046  5  Block structure not found
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Error while output of NC-block
&             Block structure not found
&             Name of block: &C03
/////////////////////////////////////////////////////////
N3C030047  5  Format definition not found
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Format definition not found &C04
&             Name of block: &C03
/////////////////////////////////////////////////////////
N3C030048  4  Error while formatting
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Variable for cooling not found
&             Formatting impossible!
&             Name of block: &C03
&             Part of block: &C04
/////////////////////////////////////////////////////////
N3C030049  4  Error while formatting
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while formatting
&             Name of block: &C03
&             Part of block: &C04
&             Format       : &C05
/////////////////////////////////////////////////////////
N3C030050  4  Few format statements
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while formatting
&             Few format statements
&             Name of block: &C03
/////////////////////////////////////////////////////////
N3C030051  4  Error in part of block
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while evaluate part &I03
&             Name of block: &C03
&             Part of block: &C04
/////////////////////////////////////////////////////////
N3C030052  5  Error while sorting variable pool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while sorting variable pool
/////////////////////////////////////////////////////////
N3C030053  5  Error while formatting
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Format statement S in part &I03 : variable unknown
&             Name of block: &C03
&             Part of block: &C04
/////////////////////////////////////////////////////////
N3C030054  4  Missing paragraph-sign for end of table
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Missing paragraph-sign for end of table
&             Name of block: &C03
/////////////////////////////////////////////////////////
N3C030055  4  Error in definition of empty line
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in definition of empty line
/////////////////////////////////////////////////////////
N3C030056  5  More than '=' sign in assignment
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             More than one '=' sign in assignment
&             Assignment            :
&             &C03
/////////////////////////////////////////////////////////
N3C030057  5  Macro: APT-line too long
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             APT-line created in macro too long
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030058  3  Macro: Format statement must follow number
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Format statement must follow number
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030059  5  Macro: Wrong APTTXT-output
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Wrong APTTXT-output, inverted comma-sign missing
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030060  4  Cycle macro can not be solved in macro!
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Cycle macro can not be solved in macro!
&             The associated block will be used.
/////////////////////////////////////////////////////////
N3C030061  5  Wrong macro command!
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Wrong macro command!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030062  5  Macro: Wrong label number!
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Wrong label number!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030063  4  Macro: Wrong interpretation!
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Wrong interpretation!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030064  5  Macro: Wrong IF-structure!
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Wrong IF-structure!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030065  5  Macro: Label number exists two times!
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Label number exists two times!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030066  4  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: double sign
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C030067  4  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: double decimal digit
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C030068  4  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: sign not allowed
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C030069  5  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: Wrong brackets
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C030070  5  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             line                  :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: variable not found
&             Variable              :
&             &C03
/////////////////////////////////////////////////////////
N3C030071  5  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: operator error
&             Operator              :
&             &C03
/////////////////////////////////////////////////////////
N3C030072  5  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: division by zero
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C030073  5  Error while index variables
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while index variables: variable with this index
&             not found
&             Index variable        :
&             &C03
/////////////////////////////////////////////////////////
N3C030074  5  Error while index variables
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while index variables: can not determine index
&             Index variable        :
&             &C03
/////////////////////////////////////////////////////////
N3C030075  5  Error while assign value
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while assign value: index of left side
&             can not be computed
&             Assign of value       :
&             &C03
/////////////////////////////////////////////////////////
N3C030076  5  Error while assigning value
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while assigning value: Wrong brackets at left side
&             Assign of value       :
&             &C03
/////////////////////////////////////////////////////////
N3C030077  5  Error in index variables
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in index variables: Wrong brackets
&             Index variable        :
&             &C03
/////////////////////////////////////////////////////////
N3C030078  5  Macro error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in 1st statement of comparing operation
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C030079  5  Macro error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in 2nd statement of comparing operation
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C030080  5  Macro error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Syntax error in comparing operation
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030081  5  Macro error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Too much connections in IF-structure
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030082  5  Macro error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Name of variable must contain at last 16 Zeichen
&             Name of variable      :
&             &C03
/////////////////////////////////////////////////////////
N3C030083  4  Macro error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Assignment of text into numerical variable
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030084  4  Macro error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Assignment of a number into text variable
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030085  5  Macro error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Right side of assignment undefined
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
////////////
////////////  TECNICAL Errors
////////////
/////////////////////////////////////////////////////////
N3C030086  4  No feedrate defined
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No (rapid) feed rate defined
/////////////////////////////////////////////////////////
N3C030087  4  No feed rate given
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No feed rate given
/////////////////////////////////////////////////////////
N3C030088  5  Can not determine turning direction
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Can not determine turning direction
/////////////////////////////////////////////////////////
N3C030089  3  Call of undefined gear
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Call of undefined gear
/////////////////////////////////////////////////////////
N3C030090  3  Inverse feed rate exceeds maximum value
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Inverse feed rate
&             &F01(13.5)
&             exceeds its maximum value
&             &F02(13.5)
/////////////////////////////////////////////////////////
N3C030091  3  Inverse feed rate falls below minimum value
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Inverse feed rate
&             &F01(13.5)
&             falls below minimum value!
&             &F02(13.5)
/////////////////////////////////////////////////////////
N3C030092  3  Maximal value of a machining axis is exceeded
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             In NC-sequence &I03 the maximal value
&             of the machining axis
&             &F02(10.3) is exceeded by &F01(10.3)
/////////////////////////////////////////////////////////
N3C030093  3  Value of machining axis falls below minimum
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             In NC-sequence &I03 the value
&             of the machining axis &F01(13.5)
&             falls below its minimum of &F02(13.5)
/////////////////////////////////////////////////////////
N3C030094  4  Spindle speed statement missing
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Feed rate depends of spindle speed and
&             spindle speed statement is missing
/////////////////////////////////////////////////////////
N3C030095  4  No tool diameter defined
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No tool diameter defined
&             CUTTER- or TOOLNO-command missing or wrong
/////////////////////////////////////////////////////////
N3C030096  4  No tool loaded
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No tool loaded
/////////////////////////////////////////////////////////
N3C030097  3  No tool selected
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No tool selected
/////////////////////////////////////////////////////////
N3C030098  4  Type of tool undefined
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Type of tool to load is undefined
&             &C03
&             Check associated TOOLNO command
/////////////////////////////////////////////////////////
N3C030099  4  Type of cycle unknown
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Unknown type of cycle is called
&             &C03
/////////////////////////////////////////////////////////
N3C030100  5  Miller position not possible
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Miller position not possible
/////////////////////////////////////////////////////////
N3C030101  3  No time statement
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No time statement for called subprogram in
&             extern file with unit-no. &I03 given.
/////////////////////////////////////////////////////////
N3C030102  5  Error in contour recalculation
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Contour recalculation must not start with a circle
/////////////////////////////////////////////////////////
N3C030103  5  Error in contour recalculation
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Contour recalculation must not start with a circle
/////////////////////////////////////////////////////////
N3C030104  3  Starting- and end-point are identical
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Starting- and end-point are identical
/////////////////////////////////////////////////////////
N3C030105  5  Error in contour recalculation
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Error while computing intersection of line and
&             circle while contour recalculation
/////////////////////////////////////////////////////////
N3C030106  5  Error in contour recalculation
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while computing intersection of line and
&             circle while contour recalculation
/////////////////////////////////////////////////////////
N3C030107  5  Error in contour recalculation
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Direction vector of circle can not be determined
&             because of inaccouracy
/////////////////////////////////////////////////////////
N3C030108  5  Error in contour recalculation
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Contour elements are not in same plane
/////////////////////////////////////////////////////////
N3C030109  3  Manual origin defined more than once
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             A manual origin is defined more than once.
&             The current origin will be replaced!
/////////////////////////////////////////////////////////
N3C030110  4  Origin not complete
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Origin data no.&I03 not complete
/////////////////////////////////////////////////////////
N3C030111  4  Undefined origin
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Undefined origin no.&I03 is called
/////////////////////////////////////////////////////////
N3C030112  4  Origin not complete
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Command for origin no.&I01 not complete
/////////////////////////////////////////////////////////
N3C030113  4  Undefined subprogram
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Call of undefined subprogram
/////////////////////////////////////////////////////////
N3C030114  4  Error after LOADTL
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Coordinates for LOADTL block can not be put in pool.
&             Traversing movement must be GOTO movement.
/////////////////////////////////////////////////////////
N3C030115  5  Error after LOADTL
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Too many ORIGIN-commands between LOADTL and 1st GOTO
/////////////////////////////////////////////////////////
N3C030116  5  MULTAX error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             A wrong plane was selected while MULTAX
/////////////////////////////////////////////////////////
N3C030117  4  MULTAX error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             MULTAX-ROTABL transformation with current axis
&             not possible
/////////////////////////////////////////////////////////
N3C030118  5  MULTAX error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             MULTAX position can not be reached. Angle
&             at &I03 . axis is greater than maximum angle.
&             &F01(13.5) > &F02(13.5)
/////////////////////////////////////////////////////////
N3C030119  5  MULTAX error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             MULTAX position can not be reached. Angle
&             at &I03 . axis is smaller than minimum angle.
&             &F01(13.5) < &F02(13.5)
/////////////////////////////////////////////////////////
N3C030120  5  Recursive macro call
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Recoursive macro call not allowed
&             Name of macro         : &C03
/////////////////////////////////////////////////////////
N3C030121  5  Macro call in cycle macro
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Macro call in cycle macro not allowed
&             Name of macro         : &C03
/////////////////////////////////////////////////////////
////////////
////////////  ERROR IN FORTRAN EXECUTION
////////////
/////////////////////////////////////////////////////////
N3C030122  4  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Coordinate with address &C03 is no number
&             Value = &C04
/////////////////////////////////////////////////////////
N3C030123  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in APT file managment
/////////////////////////////////////////////////////////
N3C030124  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while reading APT line
/////////////////////////////////////////////////////////
N3C030125  4  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Variable &C03 not found
/////////////////////////////////////////////////////////
N3C030126  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while reading file with unit &I03
/////////////////////////////////////////////////////////
N3C030127  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while open file with unit &I03
/////////////////////////////////////////////////////////
N3C030128  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in routine named before
/////////////////////////////////////////////////////////
N3C030129  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while writing file with unit &I03
&             Value = &C03
/////////////////////////////////////////////////////////
N3C030130  4  TOOLNO error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Parameter &I03 is of wrong type
/////////////////////////////////////////////////////////
N3C030131  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while open macro file
/////////////////////////////////////////////////////////
N3C030132  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while creating APT-file from macro file
/////////////////////////////////////////////////////////
N3C030133  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while cycle-APT file managment
/////////////////////////////////////////////////////////
N3C030134  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while copy from sequence- to direct-access
/////////////////////////////////////////////////////////
N3C030135  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Macro not found!
&             Name                  : &C03
/////////////////////////////////////////////////////////
//////////
//////////    ERROR WHILE INITIALISIATION
//////////
/////////////////////////////////////////////////////////
N3C030136  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Check dimension of NC blocks
&             Total amount of possible NC lines exceeded
&             for all blocks
&             Name                  : &C03
/////////////////////////////////////////////////////////
N3C030137  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in configuration of NCTOOLS
&             More fomat definitions than allowed
/////////////////////////////////////////////////////////
N3C030138  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in configuration of NCTOOLS
&             More report descriptions than allowed
/////////////////////////////////////////////////////////
N3C030139  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Wrong definition of axes in machine head
&             Machine does not match the predefined type
/////////////////////////////////////////////////////////
N3C030140  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Unknown type of 5 axes
/////////////////////////////////////////////////////////
N3C030141  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Macro-directory not defined!
/////////////////////////////////////////////////////////
N3C030142  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Address of rotary axes wrong
/////////////////////////////////////////////////////////
N3C030143  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Parameter with sign &C03 is no number
&             Change parameter definition analogical
/////////////////////////////////////////////////////////
N3C030144  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Parameter with sign &C03 is undefined
&             Change parameter definition analogical
/////////////////////////////////////////////////////////
N3C030145  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while checking blocks &C03
&             Change parameter definition analogical
/////////////////////////////////////////////////////////
N3C030146  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Wrong coordinate assignement in parameter
&             line                  : &C03
/////////////////////////////////////////////////////////
N3C030147  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Wrong priorities in parameter
&             line                  : &C03
/////////////////////////////////////////////////////////
N3C030148  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Parameter-sign        :
&             &C02
&             Subprogram            : &C01
&             Wrong priorities in parameter
/////////////////////////////////////////////////////////
N3C030149  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Dimension of variable pool not sufficient
&             Amount of variables not sufficient
/////////////////////////////////////////////////////////
N3C030150  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Dimension of variable pool not sufficient
&             Buffer for text too small
/////////////////////////////////////////////////////////
N3C030151  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in variable-pool operation
/////////////////////////////////////////////////////////
N3C030152  4  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Parameter-sign        :
&             &C02
&             Subprogram            : &C01
&             Format of sequence is V
&             Can not step back in program
/////////////////////////////////////////////////////////
N3C030153  4  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Parameter-Kennung     :
&             &C02
&             Subprogram            : &C01
&             MULTAX should be transformed in MODE as also
&             in ROTABL
&             Only ROTABL-commands will be created
/////////////////////////////////////////////////////////
N3C030154  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Parameter-Sign        :
&             &C02
&             Subprogram            : &C01
&             MULTAX transformation
&             Amount of vector components <> 3
/////////////////////////////////////////////////////////
N3C030155  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Parameter-Sign        :
&             &C02
&             Subprogram            : &C01
&             Rotatory axis is defined not correct
/////////////////////////////////////////////////////////
N3C030156  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             TURRET no.&I03 too small
/////////////////////////////////////////////////////////
N3C030157  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             TURRET no.&I03 too large
/////////////////////////////////////////////////////////
N3C030158  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Part number in MILL/ &I03 too small
/////////////////////////////////////////////////////////
N3C030159  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Part number in MILL/ &I03 too large
/////////////////////////////////////////////////////////
N3C030160  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Part number in MILL/ &I03 defined more than once
/////////////////////////////////////////////////////////
N3C030161  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Part with number &I03 involved inside
/////////////////////////////////////////////////////////
N3C030162  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Part with number &I03 not defined
/////////////////////////////////////////////////////////
N3C030163  3  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             Parameter-Kennung     :
&             &C02
&             Subprogram            : &C01
&             Feed rate repetition must not be activated
&             while feed rate computing and is switched off
/////////////////////////////////////////////////////////
////////////
////////////  ERROR WITH TOOLNO
////////////
/////////////////////////////////////////////////////////
N3C030164  4  Toolno Error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             &I03. entry in extern TOOLNO file is wrong
&             Entry                 : &C03
/////////////////////////////////////////////////////////
N3C030165  4  Toolno Error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The associated tool number is &I03
/////////////////////////////////////////////////////////
N3C030166  4  Toolno Error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             &I03. TOOLNO-statement is wrong
/////////////////////////////////////////////////////////
N3C030167  4  Toolno Error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while transform the &I03. TOOLNO-statement
/////////////////////////////////////////////////////////
N3C030168  4  TOOLNO syntax error in parameter &I03
&             Line number APT   : &I01
&             Line number Macro : &I02
&             APT-line          :
&             &C02
&             Subprogram        : &C01
&             TOOLNO syntax error in parameter &I03
&             &C03
/////////////////////////////////////////////////////////
N3C030169  4  TOOLNO Syntax Error
&             Line number APT   : &I01
&             Line number Macro : &I02
&             APT-line          :
&             &C02
&             Subprogram        : &C01
&             TOOLNO syntax error in line
&             &C03
/////////////////////////////////////////////////////////
N3C030170  4  NC-line too long
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             NC-line too long
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C030171  5  Input file error
&             Subprogram            : &C01
&             Input parameter file for CL-APT
&             transformation has not enough parameters or
&             does not exist
/////////////////////////////////////////////////////////
N3C030172  4  PP table error
&             Subprogram            : &C01
&             Error in CL-APT transformation
&             Error while reading PP table
/////////////////////////////////////////////////////////
N3C030173  4  CL file error
&             Subprogram            : &C01
&             Error in CL-APT transformation
&             Error while opening CL file
/////////////////////////////////////////////////////////
N3C030174  4  PP table error
&             Subprogram            : &C01
&             Error in CL-APT transformation
&             Code &I01 not found
/////////////////////////////////////////////////////////
N3C030175  4  PP table error
&             Subprogram            : &C01
&             Error in CL-APT transformation
&             Processed APT line is too long
/////////////////////////////////////////////////////////
N3C030176  5  PP file error
&             Subprogram            : &C01
&             Error in postprocessor file
&             File cannot be decoded
/////////////////////////////////////////////////////////
N3C030177  4  APT syntax error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Invalid SYNC - SPINDL combination in
&             APT lines between LOADTL and GOTO
/////////////////////////////////////////////////////////
N3C030178  3  Tool not defined
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Nose point radius/quadrant compensation
&             needs an active tool preselection
/////////////////////////////////////////////////////////
N3C030179  3  Stack is full
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The output stack is full and will be emptied
/////////////////////////////////////////////////////////
N3C030180  5  Parserstack is full
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Term &C03 is too complex.
/////////////////////////////////////////////////////////
N3C030181  4  Internal Error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Term &C03 cannot be calculated.
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
N3C030182  3  Warning: Check rotary angles
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Multax position cannot be reached in given direction.
&             Check angles in NC record &I03
&             1st solution: &F01(13.5)  &F02(13.5)
&             2nd solution: &F03(13.5)  &F04(13.5)
/////////////////////////////////////////////////////////
N3C030183  4  Error in CYCLE statement
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Too many movements in the cycle. The decrement
&             depth value is too small.
/////////////////////////////////////////////////////////
N3C030184  3  Error in LOADTL block
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             LOADTL block cannot access on coordinates of next
&             motion command after LOADTL. The end of APT or
&             Macro-APT has been reached.
/////////////////////////////////////////////////////////
N3C030185  5  Error in Macro
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Too many nested WHILE loops detected.
/////////////////////////////////////////////////////////
N3C030186  5  Error in Macro
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Nesting error in WHILE loop detected.
/////////////////////////////////////////////////////////
N3C030187  4  Error in Macro
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Loop with more than &I03 repetitions detected.
/////////////////////////////////////////////////////////
N3C030188  4  Error in Macro
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line            :
&             &C02
&             Subprogram         : &C01
&             Unknown macro type defined in block for
&             macro APT words
/////////////////////////////////////////////////////////
N3C030189  4  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in APT file managment
&             No motion command found before end of
&             APT file/macro APT file
/////////////////////////////////////////////////////////
N3C030190  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Vector of compensation direction cannot be
&             calculated because tool axis vector and
&             motion vector are collinear
/////////////////////////////////////////////////////////
N3C030191  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The end of the "Plotting Intermediate File" has been
&             reached. No further correction direction vector will
&             be generated.
/////////////////////////////////////////////////////////
N3C030192  3  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The motion was not programmed in "contact mode".
&             No correction direction vector will be generated.
/////////////////////////////////////////////////////////
N3C030193  3  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No correction direction vector for this motion in the
&             "Plotting Intermediate File"
&             No correction direction vector will be generated.
/////////////////////////////////////////////////////////
N3C030194  3  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No corresponding "Plotting Intermediate File" for the
&             selected APT file exists.
&             No correction direction vector will be generated.
/////////////////////////////////////////////////////////
N3C030195  3  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Calculation of intermediate points is not possible
&             during "CUTCOM/CON3D,..." and it will be deactivated
&             and reactivated after "CUTCOM/CON3D,OFF".
/////////////////////////////////////////////////////////
N3C030196  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             TDB: Attribute &C03
&             is not "MONO-VALUATED" or not of type:
&             &C04
/////////////////////////////////////////////////////////
N3C030197  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             TDB: Attribute &C03
&             Element with index &I03 not found
/////////////////////////////////////////////////////////
N3C030198  4  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             TDB: No T, P1 or P2 found for
&             attribute &C03
/////////////////////////////////////////////////////////
N3C030199  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Environment variable :
&             &C03
&             not defined.
/////////////////////////////////////////////////////////
N3C030200  5  Program error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             If circles are splitted, the first movement
&             must be a GOTO.
/////////////////////////////////////////////////////////
N3C030201  5  Technical error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Contour recalculation is activated but the Quadrant
&             of the tool is not defined.
/////////////////////////////////////////////////////////
N3C030202  5  Programming error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             It is not allowed to switch between
&             CUTCOM/LEFT and CUTCOM/RIGHT without CUTCOM/OFF
&             if contour recalculation is activated.
/////////////////////////////////////////////////////////
N3C030203  5  Programming error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The turrets &I03 and &I04 are defined as masters of
&             spindel &I05. (SYNC / &I06)
/////////////////////////////////////////////////////////
N3C030204  5  Programming error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             There is no master definition on spindel &I03.
&             (SYNC / &I04)
/////////////////////////////////////////////////////////
N3C030205  5  Programming error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Turret &I03 is no longer master on spindel &I04,
&             but doesn't take part on synchronisation &I05.
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
N3C030206  5  Fatal error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Selected parameter input file *.PPPAR contains
&             wrong machine type.
/////////////////////////////////////////////////////////
N3C030207  5  Licensing error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             User has not the necessary PPB license to start
&             this postprocessor.
/////////////////////////////////////////////////////////
N3C030208  5  Synchronisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             There is no second SYNC-statement with this number.
&             This synchronisation will be ignored.
N3C030209  5  Input file incorrect
&             Subprogram            : &C01
&             The inputfile PP_INPUT contains undefined values.
/////////////////////////////////////////////////////////
N3C030210  5  Input file incorrect
&             Subprogram            : &C01
&             Could not open file
&             &C03
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
/////////// Fehlerbehandlung Variablenpool //////////////
/////////////////////////////////////////////////////////
N3C090001  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Invalid name '&C03'
/////////////////////////////////////////////////////////
N3C090003  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             no active pool
/////////////////////////////////////////////////////////
N3C090004  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             not enough memory
/////////////////////////////////////////////////////////
N3C090005  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             variable does not exist
&             Pool                  : &C03
&             Variablename          : &C04
/////////////////////////////////////////////////////////
N3C090006  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             unknown variabletype  : &I03
&             Pool                  : &C03
&             Variablename          : &C04
/////////////////////////////////////////////////////////
N3C090009  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             invalid lenght of pool- or variablename
&             Pool                  : &C03
&             Variablename          : &C04
/////////////////////////////////////////////////////////
N3C090010  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             invalid variabletyp   : &I03
&             Pool                  : &C03
&             Variablename          : &C04
/////////////////////////////////////////////////////////
N3C090011  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             pool does not exist
&             Pool                  : &C03
/////////////////////////////////////////////////////////
N3C090012  3  Error in varpool
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             pool already exist
&             Pool                  : &C03
/////////////////////////////////////////////////////////
/// interpreter messages
/////////////////////////////////////////////////////////
N3C091001  5  Error in Macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Invalid file name of macro definition
/////////////////////////////////////////////////////////
N3C091002  5  Error in Macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             File:
&             &C03
&             has no read permission or does not exist
/////////////////////////////////////////////////////////
N3C091003  5  Error in Macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             File:
&             &C03
&             Not enough memory to load file
/////////////////////////////////////////////////////////
N3C091004  5  Error in Macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             File:
&             &C03
&             Incomplete last line
/////////////////////////////////////////////////////////
N3C091005  4  Wrong macro command!
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro command too long! Maximum is &I03!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091006  4  Macro: Wrong label number!
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Wrong label number!
&             line                  :
&             &C03
&             1 <= label number <= &I03
/////////////////////////////////////////////////////////
N3C091007  4  Macro: Wrong label number!
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Wrong label number!
&             line                  :
&             &C03
&             Label number is not defined.
/////////////////////////////////////////////////////////
N3C091008  4  Macro: Label number exists two times!
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Label exists more than once!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091009  4  Macro: Wrong IF-structure!
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Wrong IF-structure!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091010  4  Error in Macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Nesting error in WHILE loop detected.
&             No ENDWHILE before end of file
/////////////////////////////////////////////////////////
N3C091011  4  Macro error
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Syntax error in comparing operation
&             line                  :
&             &C03
&             Syntax is EXIST(variable name)
/////////////////////////////////////////////////////////
N3C091012  4  Macro error
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Syntax error in comparing operation
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091013  4  Macro error
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Too many logical operations in
&             condition
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091014  4  Macro error
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in 1st statement of comparing operation
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C091015  4  Macro error
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in 2nd statement of comparing operation
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C091016  4  Macro error
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Assignment of text into numerical variable
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091017  4  Macro error
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Assignment of text into numerical variable
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091018  4  Macro error
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Right side of assignment undefined
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091019  4  Error in Macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in WHILE loop.
&             Loop has more than &I03 repetitions.
/////////////////////////////////////////////////////////
N3C091020  4  Error in Macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in WHILE loop.
&             Too many nested WHILE loops detected.
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091021  4  Error in Macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in WHILE loop.
&             Nesting error in WHILE loop detected.
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091022  4  Macro: Wrong interpretation!
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Wrong interpretation!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091023  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Too many part strings!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091024  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Closing delimiter of constant string is missing!
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091025  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Syntax error in regular expression
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091026  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Match operation is not allowed for numbers
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091027  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in assignment
&             line                  :
&             &C03
/////////////////////////////////////////////////////////
N3C091028  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Created text too long
&             line                  :
&             &C03
&             Maximum is            : &I03
/////////////////////////////////////////////////////////
N3C091029  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: A number must be followed by a format description
&             line                  :
&             &C03
&             part of line          :
&             &C04
/////////////////////////////////////////////////////////
N3C091030  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Closing delimiter is missing
&             line                  :
&             &C03
&             part of line          :
&             &C04
/////////////////////////////////////////////////////////
N3C091031  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in format description
&             line                  :
&             &C03
&             part of line          :
&             &C04
/////////////////////////////////////////////////////////
N3C091032  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Error in part-of-string definition
&             part of line          :
&             &C04
/////////////////////////////////////////////////////////
N3C091033  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Bad format environment-variable substitution
&             line                  :
&             &C04
/////////////////////////////////////////////////////////
N3C091034  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Missing "}" in environment-variable substitution
&             line                  :
&             &C04
/////////////////////////////////////////////////////////
N3C091035  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Substituting nonexistent environment variable
&             line                  :
&             &C04
/////////////////////////////////////////////////////////
N3C091036  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Syntax error in FOPEN command
&             Correct syntax is :
&             FOPEN (<numerical expression>,'<filename>',<mode [a|n]>)
&             line                  :
&             &C04
/////////////////////////////////////////////////////////
N3C091037  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Syntax error in FOPEN command
&             FOPEN mode must be 'a' (append) or 'n' (new)
&             line                  :
&             &C04
/////////////////////////////////////////////////////////
N3C091038  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: An other file with same number (&I03)
&             has been opened. Open will be ignored.
&             Old name:&C04
&             New name:&C05
/////////////////////////////////////////////////////////
N3C091039  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Syntax error in FCLOSE command
&             Correct syntax is :
&             FCLOSE (<numerical expression>)
&             line                  :
&             &C04
/////////////////////////////////////////////////////////
N3C091040  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: Syntax error in FWRITE command
&             Correct syntax is :
&             FWRITE (<numerical expression>) <output description>
&             line                  :
&             &C04
/////////////////////////////////////////////////////////
N3C091041  4  Error in macro
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Subprogram            : &C01
&             Macro: File number &I03 is not open.
&             line                  :
&             &C04
/////////////////////////////////////////////////////////
N3C091042  4  Error in description of format
&             Line number APT       : &I01
&             Name of macro         : &C02
&             Macro-line            :
&             &C03
&             Subprogram            : &C01
&             Error in description of format in the macro-definition
&             &C04
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
////////////// Fehlerbehandlung Parser///////////////////
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
N3C090501  4  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: double sign
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
// war N3C030067
N3C090502  4  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: double decimal digit
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C090503  4  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: sign not allowed
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
N3C090504  4  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: Wrong brackets
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
// war N3C030070
N3C090505  5  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             line                  :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: variable not found
&             Variable              :
&             &C03
/////////////////////////////////////////////////////////
// war N3C030071
N3C090506  5  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: operator error
&             Operator              :
&             &C03
/////////////////////////////////////////////////////////
N3C090507  5  Error in mathematical sequence
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error in mathematical sequence: division by zero
&             Sequence              :
&             &C03
/////////////////////////////////////////////////////////
// war N3C030180
N3C090508  5  Parserstack is full
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Term &C03 is too complex.
/////////////////////////////////////////////////////////
// war N3C030181
N3C090509  5  Internal Error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Term &C03 cannot be calculated.
/////////////////////////////////////////////////////////
// war N3C030073
/ behandelt FEHLER 90510 und FEHLER 90511
N3C090510  5  Error while index variables
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Error while index variables: variable with this index
&             not found
&             Index variable        :
&             &C03
/////////////////////////////////////////////////////////
N3C090512  5  Memory error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             not enough memory for temporary variable
&             Input                 :
&             &C03
/////////////////////////////////////////////////////////
N3C090513  5  Error while index variables
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             the index depth of a variable is too high
&             &C03
/////////////////////////////////////////////////////////
N3C090514  5  String error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             the inputstring is too long
&             Input                 :
&             &C03
/////////////////////////////////////////////////////////
N3C090515  4  String error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             the inputstring is a NULL-pointer
/////////////////////////////////////////////////////////
N3C090516  5  Error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             term is too complex
&             too much temporary variables needed
&             Input                 :
&             &C03
/////////////////////////////////////////////////////////
N3C090517  4  Error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             The index is too complex for
&             these subroutine
&             Input                 :
&             &C03
/////////////////////////////////////////////////////////
N3C090518  4  Error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Syntax Error
&             Input                 :
&             &C03
/////////////////////////////////////////////////////////
N3C090519  4  Error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             No arguments for the function
&             Function              : &C03
&             Right number          : &I03
/////////////////////////////////////////////////////////
N3C090520  4  Error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Number of arguments for function is wrong
&             Function              : &C03
&             Wrong number          : &I03
&             Right number          : &I04
/////////////////////////////////////////////////////////
N3C090521  4  Error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Function is not allowed in parser
&             Function              : &C03
/////////////////////////////////////////////////////////
N3C090522  4  Error while parser
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Character not allowed in variablename
&             Variable              :
&             &C03
// war N3C030149 ist/wird abgeschafft
N3C090599  5  Initialisation error
&             Line number APT       : &I01
&             Line number Macro-APT : &I02
&             APT-line              :
&             &C02
&             Subprogram            : &C01
&             Dimension of variable pool not sufficient
&             Amount of variables not sufficient
/////////////////////////////////////////////////////////
