/*
 * DO NOT MODIFY THIS FILE!!!!
 * THIS FILE IS AUTOMATICALLY GENERATED!!!
*/
#ifndef LCM_AUTLciVMPredefined_STUB_H
#define LCM_AUTLciVMPredefined_STUB_H

#include "AUTLciVMExterns.h"
/* Include C header file that contains external definitions */
#include "AUTLciVMPredefined.h"
#include "AUTLcmxData_stub.h"
ExportedByAUTLciVMExternsC void install_AUTLciVMPredefined(); /* This function must be called inside function 'install_lcm_extern' of file 'extern_stub.c' */

/* Default assign and comparison functions for extern types */

ExportedByAUTLciVMExternsC value LCMBool_create(LCMBool x);

ExportedByAUTLciVMExternsC value pure_create(pure x);

ExportedByAUTLciVMExternsC value LCMInt8_create(LCMInt8 x);

ExportedByAUTLciVMExternsC value LCMInt16_create(LCMInt16 x);

ExportedByAUTLciVMExternsC value LCMInt32_create(LCMInt32 x);

ExportedByAUTLciVMExternsC value LCMInt64_create(LCMInt64 x);

ExportedByAUTLciVMExternsC value LCMUint8_create(LCMUint8 x);

ExportedByAUTLciVMExternsC value LCMUint16_create(LCMUint16 x);

ExportedByAUTLciVMExternsC value LCMUint32_create(LCMUint32 x);

ExportedByAUTLciVMExternsC value LCMUint64_create(LCMUint64 x);

ExportedByAUTLciVMExternsC value LCMFloat32_create(LCMFloat32 x);

ExportedByAUTLciVMExternsC value LCMFloat64_create(LCMFloat64 x);

ExportedByAUTLciVMExternsC value LCMFloat128_create(LCMFloat128 x);

ExportedByAUTLciVMExternsC value LCMString8_create(LCMString8 x);

ExportedByAUTLciVMExternsC value LCMChar8_create(LCMChar8 x);

ExportedByAUTLciVMExternsC value LCMWord8_create(LCMWord8 x);

ExportedByAUTLciVMExternsC value LCMWord16_create(LCMWord16 x);

ExportedByAUTLciVMExternsC value LCMWord32_create(LCMWord32 x);

ExportedByAUTLciVMExternsC value LCMWord64_create(LCMWord64 x);


#endif


