/*
 * DO NOT MODIFY THIS FILE!!!!
 * THIS FILE IS AUTOMATICALLY GENERATED!!!
*/
#ifndef LCM_AUTLcmxData_STUB_H
#define LCM_AUTLcmxData_STUB_H

#include "AUTLciVMExterns.h"
/* Include C header file that contains external definitions */
#include "AUTLcmxData.h"
ExportedByAUTLciVMExternsC void install_AUTLcmxData(); /* This function must be called inside function 'install_lcm_extern' of file 'extern_stub.c' */

/* Default assign and comparison functions for extern types */

ExportedByAUTLciVMExternsC value AUTLcmxDataPtr_create(AUTLcmxDataPtr x);

ExportedByAUTLciVMExternsC value AUTLcmxRecordPtr_create(AUTLcmxRecordPtr x);

ExportedByAUTLciVMExternsC value AUTLcmxTuplePtr_create(AUTLcmxTuplePtr x);

ExportedByAUTLciVMExternsC value AUTLcmxScalarPtr_create(AUTLcmxScalarPtr x);

ExportedByAUTLciVMExternsC value AUTLcmxArrayPtr_create(AUTLcmxArrayPtr x);

ExportedByAUTLciVMExternsC value voidPtr_create(voidPtr x);

ExportedByAUTLciVMExternsC value LCMInt32Ptr_create(LCMInt32Ptr x);


#endif


