RUNSTATS ON TABLE adl.mo_db_version      WITH DISTRIBUTION AND INDEXES ALL SHRLEVEL REFERENCE;
COMMIT;
RUNSTATS ON TABLE adl.mo_lock            WITH DISTRIBUTION AND INDEXES ALL SHRLEVEL REFERENCE;
COMMIT;
RUNSTATS ON TABLE adl.mo_rec_obj         WITH DISTRIBUTION AND INDEXES ALL SHRLEVEL REFERENCE;
COMMIT;
RUNSTATS ON TABLE adl.mo_rec_obj_param   WITH DISTRIBUTION AND INDEXES ALL SHRLEVEL REFERENCE;
COMMIT;
RUNSTATS ON TABLE adl.mo_command         WITH DISTRIBUTION AND INDEXES ALL SHRLEVEL REFERENCE;
COMMIT;
RUNSTATS ON TABLE adl.mo_command_cm_ctxt WITH DISTRIBUTION AND INDEXES ALL SHRLEVEL REFERENCE;
COMMIT;

