-- COPYRIGHT 2004 DASSAULT SYSTEMES

-- Description:
-- ORACLE SQL commands used to create tables and view for UDDI persistency


-- Creation of tables
CREATE TABLE DESCRIP(
				"PARENTKEY" VARCHAR2(41) ,
				"LANG" VARCHAR2(8) ,
				"VALUE" VARCHAR2(256));

CREATE TABLE BINDINGT(
				"UDDIKEY" VARCHAR2(41) ,
				"SERVICEKEY" VARCHAR2(41) ,
				"ACCESSPOINT" VARCHAR2(255),
				"URLTYPE" VARCHAR2(64));

CREATE TABLE INSTDET(
				"UDDIKEY" VARCHAR2(41) ,
				"BINDINGKEY" VARCHAR2(41) ,
				"TMODELKEY" VARCHAR2(41),
				"PARAMS" VARCHAR2(255));

CREATE TABLE OVERVIEW(
				"UDDIKEY" VARCHAR2(41) ,
				"PARENTKEY" VARCHAR2(41) ,
				"OVURL" VARCHAR2(255));

CREATE TABLE BUSINESS(
				"UDDIKEY" VARCHAR2(41) ,
				"OPERATOR" VARCHAR2(255) ,
				"AUTHNAME" VARCHAR2(255));

CREATE TABLE UDDINAME(
				"PARENTKEY" VARCHAR2(41) ,
				"LANG" VARCHAR2(8) ,
				"VALUE" VARCHAR2(255));

CREATE TABLE DISCOURL(
				"PARENTKEY" VARCHAR2(41) ,
				"USETYPE" VARCHAR2(255) ,
				"VALUE" VARCHAR2(255));

CREATE TABLE EMAIL(
				"PARENTKEY" VARCHAR2(41) ,
				"USETYPE" VARCHAR2(255) ,
				"VALUE" VARCHAR2(255));

CREATE TABLE PHONE(
				"PARENTKEY" VARCHAR2(41) ,
				"USETYPE" VARCHAR2(255) ,
				"VALUE" VARCHAR2(255));

CREATE TABLE ADDRLINE(
				"PARENTKEY" VARCHAR2(41) ,
				"KEYNAME" VARCHAR2(255) ,
				"KEYVALUE" VARCHAR2(255) ,
				"VALUE" VARCHAR2(80));

CREATE TABLE ADDRESS(
				"UDDIKEY" VARCHAR2(41) ,
				"PARENTKEY" VARCHAR2(41) ,
				"USETYPE" VARCHAR2(255) ,
				"SORTCODE" VARCHAR2(10) ,
				"TMODELKEY" VARCHAR2(41));

CREATE TABLE CONTACT(
				"UDDIKEY" VARCHAR2(41) ,
				"PARENTKEY" VARCHAR2(41) ,
				"USETYPE" VARCHAR2(255) ,
				"PERSONNAME" VARCHAR2(255));

CREATE TABLE IDBAG(
				"PARENTKEY" VARCHAR2(41) ,
				"TMODELKEY" VARCHAR2(41) ,
				"KEYNAME" VARCHAR2(255) ,
				"KEYVALUE" VARCHAR2(255));

CREATE TABLE CATBAG(
				"PARENTKEY" VARCHAR2(41) ,
				"TMODELKEY" VARCHAR2(41) ,
				"KEYNAME" VARCHAR2(255) ,
				"KEYVALUE" VARCHAR2(255));

CREATE TABLE BSERVICE(
				"UDDIKEY" VARCHAR2(41) ,
				"BUSINESSKEY" VARCHAR2(41));

CREATE TABLE TMODEL(
				"UDDIKEY" VARCHAR2(41) ,
				"OPERATOR" VARCHAR2(255) ,
				"AUTHNAME" VARCHAR2(255));

