#! /bin/ksh
export CATDefaultEnvironment="ReleaseManagerEnvironment"
export CATTraDecDir="/dev/null"
case `uname` in
AIX)
if [[ -z "$RELEASECLIENT_OLD_LIBPATH" && -z "$RELEASECLIENT_OLD_PATH" ]]
then export RELEASECLIENT_OLD_LIBPATH="$LIBPATH"
export LIBPATH="$RELEASEMANAGER_PATH/code/bin:$LIBPATH"
fi;;
HP-UX)
if [[ -z "$RELEASECLIENT_OLD_SHLIB_PATH" && -z "$RELEASECLIENT_OLD_PATH" ]]
then export RELEASECLIENT_OLD_SHLIB_PATH="$SHLIB_PATH"
export SHLIB_PATH="$RELEASEMANAGER_PATH/code/bin:$SHLIB_PATH"
fi;;
IRIX | IRIX64)
if [[ -z "$RELEASECLIENT_OLD_LD_LIBRARY_PATH" && -z "$RELEASECLIENT_OLD_PATH" ]]
then export RELEASECLIENT_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH"
fi;;
SunOS)
if [[ -z "$RELEASECLIENT_OLD_LD_LIBRARY_PATH" && -z "$RELEASECLIENT_OLD_PATH" ]]
then export RELEASECLIENT_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH"
fi;;
Linux) 
if [[ -z "$RELEASECLIENT_OLD_LD_LIBRARY_PATH" && -z "$RELEASECLIENT_OLD_PATH" ]]
then export RELEASECLIENT_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH"
fi
export PWD="$PWD";;
Darwin)
if [[ -z "$RELEASECLIENT_OLD_DYLD_LIBRARY_PATH" && -z "$RELEASECLIENT_OLD_PATH" ]]
then export RELEASECLIENT_OLD_DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$DYLD_LIBRARY_PATH"
fi;;
esac
if [[ -z "$RELEASECLIENT_OLD_PATH" ]]
then export RELEASECLIENT_OLD_PATH="$PATH"
case `uname` in
AIX | HP-UX | IRIX | IRIX64 | SunOS | Linux | Darwin)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH";;
Windows_NT)
export PATH="$RELEASEMANAGER_PATH/code/bin;$PATH";;
esac
fi
ReleaseClient "$@"
rc=$?
PATH="$RELEASECLIENT_OLD_PATH"
unset RELEASECLIENT_OLD_PATH
case `uname` in
AIX)
LIBPATH="$RELEASECLIENT_OLD_LIBPATH"
unset RELEASECLIENT_OLD_LIBPATH;;
HP-UX)
SHLIB_PATH="$RELEASECLIENT_OLD_SHLIB_PATH"
unset RELEASECLIENT_OLD_SHLIB_PATH;;
IRIX | IRIX64)
LD_LIBRARY_PATH="$RELEASECLIENT_OLD_LD_LIBRARY_PATH"
unset RELEASECLIENT_OLD_LD_LIBRARY_PATH;;
SunOS)
LD_LIBRARY_PATH="$RELEASECLIENT_OLD_LD_LIBRARY_PATH"
unset RELEASECLIENT_OLD_LD_LIBRARY_PATH;;
Linux)
LD_LIBRARY_PATH="$RELEASECLIENT_OLD_LD_LIBRARY_PATH"
unset RELEASECLIENT_OLD_LD_LIBRARY_PATH;;
Darwin)
DYLD_LIBRARY_PATH="$RELEASECLIENT_OLD_DYLD_LIBRARY_PATH"
unset RELEASECLIENT_OLD_DYLD_LIBRARY_PATH;;
esac
exit $rc
