#! /bin/ksh
export RELEASECONTROL_OLD_PATH="$PATH"
export CATDefaultEnvironment="ReleaseManagerEnvironment"
export CATTraDecDir="/dev/null"
case `uname` in
AIX)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASECONTROL_OLD_LIBPATH="$LIBPATH"
export LIBPATH="$RELEASEMANAGER_PATH/code/bin:$LIBPATH";;
HP-UX)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASECONTROL_OLD_SHLIB_PATH="$SHLIB_PATH"
export SHLIB_PATH="$RELEASEMANAGER_PATH/code/bin:$SHLIB_PATH";;
IRIX | IRIX64)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASECONTROL_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH";;
SunOS)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASECONTROL_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH";;
Linux)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASECONTROL_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH"
export PWD="$PWD";;
Darwin)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASECONTROL_OLD_DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$DYLD_LIBRARY_PATH";;
Windows_NT)
export PATH="$RELEASEMANAGER_PATH/code/bin;$PATH";;
esac
ReleaseControl "$@"
rc=$?
PATH="$RELEASECONTROL_OLD_PATH"
unset RELEASECONTROL_OLD_PATH
case `uname` in
AIX)
LIBPATH="$RELEASECONTROL_OLD_LIBPATH"
unset RELEASECONTROL_OLD_LIBPATH;;
HP-UX)
SHLIB_PATH="$RELEASECONTROL_OLD_SHLIB_PATH"
unset RELEASECONTROL_OLD_SHLIB_PATH;;
IRIX | IRIX64)
LD_LIBRARY_PATH="$RELEASECONTROL_OLD_LD_LIBRARY_PATH"
unset RELEASECONTROL_OLD_LD_LIBRARY_PATH;;
SunOS)
LD_LIBRARY_PATH="$RELEASECONTROL_OLD_LD_LIBRARY_PATH"
unset RELEASECONTROL_OLD_LD_LIBRARY_PATH;;
Linux) 
LD_LIBRARY_PATH="$RELEASECONTROL_OLD_LD_LIBRARY_PATH"
unset RELEASECONTROL_OLD_LD_LIBRARY_PATH;;
Darwin)
DYLD_LIBRARY_PATH="$RELEASECONTROL_OLD_DYLD_LIBRARY_PATH"
unset RELEASECONTROL_OLD_DYLD_LIBRARY_PATH;;
esac
exit $rc
