#! /bin/ksh

#***********************************************************************
#   Purpose     : 
#   Assumptions : 
#   Author      : 
#   Languages   : Shell Unix
#   Locales     : English 
#   CATIA Level : V5R8 
#***********************************************************************

set -xv

Signal=/u/temp/signal2.txt                             # Localization of the directory where signal is stored and name of the signal.
ReportFile=/u/release2/ReportFile.txt                  # File containing the progress of the shell.
Location=/u/product_directory/product2.CATProduct      # Directory where the CATProduct or the .psn are stored.
WorkingFile=/u/release2/DocToProcess.txt               # File read by the batch CATDMUBuilder to localize the product to treat.
OutPutData=/u/release2/outputdata                      # Directory where will be stored the CATProduct generated by the batch.
EndingFile=/u/release2/EndingFile.txt                  # File announcing the end of the job, the day and time of the end.


# ---------------------------
# Location of the CATProduct
# ---------------------------
echo $Location > $WorkingFile


# ---------------------------
# Treatment of the CATProduct
# ---------------------------
CATDMUBuilder $WorkingFile -product $OutPutData 2> $ReportFile

# ---------------------------
# Announce the end of the job
# ---------------------------
echo "The shell has just finished its job. Now, you can work." > $EndingFile
date '+Hour:%T' >> $EndingFile
date '+Day:%D' >> $EndingFile

# ---------------------------
# Send a signal
# ---------------------------
echo "End of this shell" > $Signal
