@echo on

rem ***********************************************************************
rem    Purpose     : 
rem    Assumptions : You need to have mapped the Unix drive on the NT workstation.
rem    Author      : 
rem    Languages   : Batch programmation
rem    Locales     : English 
rem    CATIA Level : V5R8 
rem ***********************************************************************


rem ---------------------------
rem Definition of the Variables
rem ---------------------------

set Signal1=F:\data\temp\signal1.txt                        # Localization of the directory where signal is stored and name of the signal.
set Signal2=F:\data\temp\signal2.txt
set ReportFile=C:\user\ReportFile.txt                       # File containing the progress of the shell.
set Location=C:\user\product_directory                     # Directory where the CATProduct or the .psn are stored.
set WorkingFile=C:\user\DocToProcess.txt                    # File read by the batch CATDMUBuilder to localize the product to treat.
set OutPutData=C:\user\outputdata                           # Directory where will be stored the CATProduct generated by the batch.
set EndingFile=C:\user\EndingFile.txt                       # File announcing the end of the job, the day and time of the end.


rem -------------------------
rem Loop until signal is sent
rem -------------------------

:beginning
if exist %Signal1% goto suite1 
sleep 10
goto beginning
:suite1
if exist %Signal2% goto suite
sleep 10
goto beginning
:suite

rem ------------------------
rem Treatment of a directory
rem ------------------------
CATDMUBuilder.exe %Location% -product %OutPutData% > %ReportFile%
