#! /bin/ksh
#***********************************************************************
#   Purpose     : 
#   Assumptions : To have launched the server from which the CATVpm is.
#   Author      : 
#   Languages   : Shell Unix
#   Locales     : English 
#   CATIA Level : V5R8 
#***********************************************************************
set -xv

InputFile=/u/Input/FileInput.txt                       # File read by the batch CATDMUBuilder to localize the CATVpm to treat.
ServerName=                                            # Name of the server used
UserName=                                              # User name to log on this server
Password=                                              # Password to log on this server
Role=VPMDESIGNER                                       # Role to log on this server
ReportFile=/u/user/ReportFile.txt                      # File containing the progress of the shell.
OutPutData=/u/user/outputdata                          # Directory where will be stored the CATProduct generated by the batch.
EndingFile=/u/user/EndingFile.txt                      # File announcing the end of the job, the day and time of the end.


#========================================
# Create files containing the description
#========================================

VPMFile1=/u/Input/CATVpm_root.CATVpm
"3D3D964A1CA621D4" > $VPMFile1
"3030303030303030" >> $VPMFile1
"VPMENV1 " >> $VPMFile1
"PART_LIST         " >> $VPMFile1

VPMFile2=/u/Input/CATVpm_root2.CATVpm
"3D3D964A1CA621D4" > $VPMFile2
"3030303030303030" >> $VPMFile2
"VPMENV1 " >> $VPMFile2
"PART_LIST         " >> $VPMFile2



#===================
# Writting in a file
#===================
echo $VPMFile1 > $InputFile
echo $VPMFile2 >> $InputFile


#===================================================================
# Treatment of the CATVpm files
#===================================================================
CATDMUBuilder $InputFile -server $ServerName -user $UserName -spwd $Password -role $Role -product $OutPutData 2> $ReportFile


#===================================================================
# Announce the end of the job
#===================================================================
echo "The shell has just finished its job. Now, you can work." > $EndingFile
date '+Hour:%T' >> $EndingFile
date '+Day:%D' >> $EndingFile
