#! /bin/ksh

#***********************************************************************
#   Purpose     : 
#   Assumptions : 
#   Author      : 
#   Languages   : Shell Unix
#   Locales     : English 
#   CATIA Level : V5R8 
#***********************************************************************

set -xv


Signal=/u/temp/signal.txt                              # Localization of the directory where signal is stored and name of the signal.
Tempo=30                                               # Duration of the loop (in seconds).
ReportFile=/u/user/ReportFile.txt                      # File containing the progress of the shell.
Location=/u/product_directory/                         # Directory where the CATProduct are stored.
OutPutData=/u/user/outputdata                          # Directory where will be stored the CATProduct generated by the batch.
EndingFile=/u/user/EndingFile.txt                      # File announcing the end of the job, the day and time of the end.


# -------------------------------
# Loop until signal is dispatched
# -------------------------------
while [ ! -f $Signal ]
do 
sleep $Tempo
done


# ---------------------------
# Treatment of the directory
# ---------------------------
CATDMUBuilder $Location -product $outputdata 2> $ReportFile

# ---------------------------
# Announce the end of the job
# ---------------------------
echo "The shell has just finished its job. Now, you can work." > $EndingFile
date '+Hour:%T' >> $EndingFile
date '+Day:%D' >> $EndingFile
