#! /bin/ksh

#***********************************************************************
#   Purpose     : 
#   Assumptions : 
#   Author      : 
#   Languages   : Shell Unix
#   Locales     : English 
#   CATIA Level : V5R8 
#***********************************************************************

set -xv

ReportFile=/u/user/ReportFile.txt                      # File containing the progress of the shell.
Location=/u/product_directory/product.CATProduct       # Directory where the CATProduct are stored.
WorkingFile=/u/user/DocToProcess.txt                   # File read by the batch CATDMUBuilder to localize the product to treat.
OutPutData=/u/user/outputdata                          # Directory where will be stored the CATProduct generated by the batch.
EndingFile=/u/user/EndingFile.txt                      # File announcing the end of the job, the day and time of the end.


# ---------------------------
# Location of the CATProduct
# ---------------------------
echo $Location > $WorkingFile

# ---------------------------
# Treatment of the CATProduct
# ---------------------------
CATDMUBuilder $WorkingFile -product $outputdata 2> $ReportFile

# ---------------------------
# Announce the end of the job
# ---------------------------
echo "The shell has just finished its job. Now, you can work." > $EndingFile
date '+Hour:%T' >> $EndingFile
date '+Day:%D' >> $EndingFile
