#! /bin/ksh

#***********************************************************************
#   Purpose     : 
#   Assumptions : 
#   Author      : 
#   Languages   : Shell Unix
#   Locales     : English 
#   CATIA Level : V5R8 
#***********************************************************************

set -xv

Signal=/u/temp/signal.txt                              # Localization of the directory where signal is stored and name of the signal.
ReportFile=/u/release/ReportFile.txt                   # File containing the progress of the shell.
Location=/u/product_directory/product.CATProduct       # Directory where the CATProduct is stored.
WorkingFile=/u/release/DocToProcess.txt                # File read by the batch CATDMUBuilder to localize the product to treat.
OutPutData=/u/release/outputdata                       # Directory where will be stored the CATProduct generated by the batch.
EndingFile=/u/release/EndingFile.txt                   # File announcing the end of the job, the day and time of the end.


# ---------------------------
# Location of the CATProduct
# ---------------------------
echo $Location > $WorkingFile


# ---------------------------
# Treatment of a CATProduct
# ---------------------------
CATDMUBuilder $WorkingFile -product $OutPutData 2> $ReportFile


# ---------------------------
# Announce the end of the job
# ---------------------------
echo "The shell has just finished its job. Now, you can work." > $EndingFile
date '+Hour:%T' >> $EndingFile
date '+Day:%D' >> $EndingFile

# ---------------------------
# Send a signal
# ---------------------------
echo "End of this shell" > $Signal
