#! /bin/ksh

#***********************************************************************
#   Purpose     : 
#   Assumptions : To have launched the server from which the psn is.
#   Author      : 
#   Languages   : Shell Unix
#   Locales     : English 
#   CATIA Level : V5R8 
#***********************************************************************

set -xv


ServerName=                                            # Name of the server used
UserName=                                              # User name to log in this server
Password=                                              # Password to log in this server
Role=VPMDESIGNER                                       # Role to log in this server
ReportFile=/u/user/ReportFile.txt                      # File containing the progress of the shell.
Location=/u/product_directory/product.psn              # Directory where the psn files are stored.
Location2=/u/product_directory/product2.psn
WorkingFile=/u/user/DocToProcess.txt                   # File read by the batch CATDMUBuilder to localize the product to treat.
OutPutData=/u/user/outputdata                          # Directory where will be stored the CATProduct generated by the batch.
EndingFile=/u/user/EndingFile.txt                      # File announcing the end of the job, the day and time of the end.


#===================================================================
# Create files containing the description
#===================================================================
echo $Location > $WorkingFile
echo $Location2 >> $WorkingFile

#===================================================================
# Treat
#===================================================================
CATDMUBuilder $WorkingFile -server $ServerName -user $UserName -spwd $Password -role $Role -product $OutPutData 2> $ReportFile

#===================================================================
# Announce the end of the job
#===================================================================
echo "The shell has just finished its job. Now, you can work." > $EndingFile
date '+Hour:%T' >> $EndingFile
date '+Day:%D' >> $EndingFile
