#!/bin/ksh
echo "Starting 64bits process: CATELFLanczosSlave"

for DirInCATInstallPath in `echo $CATInstallPath | tr ':' '  ' | awk '{ for (i=1; i<=NF;i++) print $i;} '`
do
  if [ -f $DirInCATInstallPath/code/binEST64/CATElfEnv64.env ]
  then
     export CAT_EST_BIN64=$DirInCATInstallPath/code/binEST64
     break
  fi
done

. $CAT_EST_BIN64/CATElfEnv64.env

$CAT_EST_BIN64/CATELFLanczosSlave
