set TIMING ON
ANALYZE TABLE adl.central_db_version ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.site               ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.database           ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.workspace_tree     ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.ws_tree_in_db      ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.multi_tree_ws_c_db ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.workspace_c_db     ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.contents_server    ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.history_event      ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.associated_comment ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.file_type          ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE adl.change_set_c_db    ESTIMATE STATISTICS SAMPLE 20 PERCENT;

