#@echo off
rem =======================================
rem TCK Management profile 1.1
rem Generated by TCK installation procedure
rem Copyright Dassault-Systemes 2000
rem =======================================

set JAVA_ROOT_PATH=C:\jdk1.1.8
set VBTMIGRATEPATH=%~dp0

set CATICPath=%MkmkIC_PATH%

set CNEXT_LEVEL=%MkmkMACRO_LEVEL%\CNEXTLVL

set LEVEL=%MkmkMACRO_LEVEL%\LEVEL

set OS_LEVEL=%MkmkMACRO_LEVEL%\%MkmkOS_NAME%

set CMD_NAME=CATVBTMaskMigrateM.exe

if NOT EXIST "%VBTMIGRATEPATH%..\bin\%CMD_NAME%" (
echo ERROR : %VBTMIGRATEPATH%..\bin\%CMD_NAME% not found
goto :EOF
)
"%VBTMIGRATEPATH%..\bin\%CMD_NAME%"


