@echo off
set RELEASEMANAGER_COMMAND=%*
IF NOT DEFINED RELEASECLIENT_OLD_PATH GOTO LABEL_NOOLDPATH
set PATH=%RELEASECLIENT_OLD_PATH%
set RELEASECLIENT_OLD_PATH=
:LABEL_NOOLDPATH
IF NOT DEFINED RELEASEMANAGER_PATH GOTO LABEL_NOPATH
call "%RELEASEMANAGER_PATH%\code\command\ReleaseDataGHHTW.bat"
call "%RELEASEMANAGER_PATH%\code\command\ReleaseDataSNU.bat"
:LABEL_NOPATH
IF NOT DEFINED RELEASEMANAGER_STARTER GOTO LABEL_WITHOUT
title %RELEASEMANAGER_STARTER% %*
call %RELEASEMANAGER_STARTER% %*
EXIT
:LABEL_WITHOUT
title %RELEASEMANAGER_COMMAND%
call %RELEASEMANAGER_COMMAND%
EXIT

