#! /bin/ksh
export RELEASESERVER_OLD_PATH="$PATH"
if [ -d "$RELEASEMANAGER_PATH/code/productIC" ] ; then
export CATICPath="$RELEASEMANAGER_PATH/code/productIC"
fi
export CATDefaultEnvironment="ReleaseManagerEnvironment"
export CATUserSettingPath="/dev/null"
export CATTraDecDir="/dev/null"
case `uname` in
AIX)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASESERVER_OLD_LIBPATH="$LIBPATH"
export LIBPATH="$RELEASEMANAGER_PATH/code/bin:$LIBPATH";;
HP-UX)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASESERVER_OLD_SHLIB_PATH="$SHLIB_PATH"
export SHLIB_PATH="$RELEASEMANAGER_PATH/code/bin:$SHLIB_PATH";;
IRIX | IRIX64)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASESERVER_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH";;
SunOS)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASESERVER_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH";;
Linux)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASESERVER_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$LD_LIBRARY_PATH"
export PWD="$PWD";;
Darwin)
export PATH="$RELEASEMANAGER_PATH/code/bin:$PATH"
export RELEASESERVER_OLD_DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="$RELEASEMANAGER_PATH/code/bin:$DYLD_LIBRARY_PATH";;
Windows_NT)
export PATH="$RELEASEMANAGER_PATH/code/bin;$PATH";;
esac
ReleaseServer "$@"
rc=$?
PATH="$RELEASESERVER_OLD_PATH"
unset RELEASESERVER_OLD_PATH
case `uname` in
AIX)
LIBPATH="$RELEASESERVER_OLD_LIBPATH"
unset RELEASESERVER_OLD_LIBPATH;;
HP-UX)
SHLIB_PATH="$RELEASESERVER_OLD_SHLIB_PATH"
unset RELEASESERVER_OLD_SHLIB_PATH;;
IRIX | IRIX64)
LD_LIBRARY_PATH="$RELEASESERVER_OLD_LD_LIBRARY_PATH"
unset RELEASESERVER_OLD_LD_LIBRARY_PATH;;
SunOS)
LD_LIBRARY_PATH="$RELEASESERVER_OLD_LD_LIBRARY_PATH"
unset RELEASESERVER_OLD_LD_LIBRARY_PATH;;
Linux) 
LD_LIBRARY_PATH="$RELEASESERVER_OLD_LD_LIBRARY_PATH"
unset RELEASESERVER_OLD_LD_LIBRARY_PATH;;
Darwin)
DYLD_LIBRARY_PATH="$RELEASESERVER_OLD_DYLD_LIBRARY_PATH"
unset RELEASESERVER_OLD_DYLD_LIBRARY_PATH;;
esac
exit $rc
