<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 ABT - CATIA - AUTOMOTIVE BODY IN WHITE TEMPLATES 2 Product
M6 1 2845
M7 1 2
M9 1 Addon
M9 1 Shareable
M4 1 A0_GSO_API_ABTAuthorized
M4 1 SDS_WorkOnSupport3D_Authorized
M1 1 GSD.prd
M2 1 CATBIWDesignInterfaces
M3 2 CATBIWDesignInterfaces,2
M2 1 CATBIWDesignModel
M3 2 CATBIWDesignModel,2
M2 1 CATBIWDesignUI
M3 2 CATBIWDesignUI,2
M2 1 CATBIWDesignWorkbench
M3 2 CATBIWDesignWorkbench,2
M19 1 SdgEnglish
M19 1 KwrEnglish
M19 1 ICONS
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 CfySamples
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
EOF
axCMvDw3sUxrl0JvEU9JBEjYXnl2Cw0IaAcO6F8OViDGCLcj2OuFdTxR8Pw084TjHRVHOlr8fleK4OccIJzWw6FeF1jGlNEjW7Fjp37ireA0bYlqgHeU3OZK8DCv+9IpOwoglFXunQhcgd9SW1hh9A1JNmSZaSeNGH3ZeXOP6P/UqinmliGkWXXLLk0ZpMfJrmGotOLy1/v4RKt8brKDDEjMTepG9thfnjFHkeGC3tRX0NLdTX7AGo+LZmEkgtvaRJ3ynC9DwX7XWMBgvgwkxq3gX1N5GkjXOH+TsYnOiCSgpxtjy9qljIOxrY1KGh5pxh2VzzCh8yA+uufIqqP7KA==
