<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 ADD - CATIA - Advanced Design Migration Configuration
M7 1 2
M6 1 2030
M2 1 GSD.prd
M3 2 GSD.prd,2
M2 1 ID1.prd
M3 2 ID1.prd,1
M2 1 PDG.prd
M3 2 PDG.prd,2
M2 1 GDR.prd
M3 2 GDR.prd,2
M2 1 V4I.prd
M3 2 V4I.prd,2
M2 1 CO1.prd
M3 2 CO1.prd,1
M2 1 COM.prd
M3 2 COM.prd,2
M2 1 Z7Z.prd
M3 2 Z7Z.prd,2
M2 1 CC1.prd
M3 2 CC1.prd,2
M24 1 E5I.prd
M3 2 E5I.prd,1
EOF
QgIKKrFRCIe9pufqX2DHcbsEIr+NZvNgNUMRxkLTvgmov207MLXHn2Tu0M3vBqylJ2ih9OV632qe39bmZ+5IqfTkOHdrgETwrofLoRs1lhZzfxdE0HsY0ycvAaAk+p7ScTcAbpq6vblXSlHEWkh96t2HeYNR02EASJbq9L9e8EOF6dsU1Pm7hSSFaElENdnSi2NoiFdLRHR5+hSohdCWgq4VTd8Vehfa2s/UyB/j6p5hgFjcmn+qUnzO5GCXrD0BpK6NNcSXCYwXbesu8gB6ah+90zsJB1F55K+BCPjBKG8L73hZ7PxeyjpHk3SSXIqBdxWP67kXpVLIfh8kanbu5A==
