<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 AM2 - CATIA - DESIGNER & ADVANCED MACHINIST 2 Configuration
M7 1 2
M6 1 2861
M2 1 AMG.prd
M3 2 AMG.prd,2
M2 1 NCG.prd
M3 2 NCG.prd,2
M2 1 NVG.prd
M3 2 NVG.prd,2
M2 1 GS1.prd
M3 2 GS1.prd,1
M2 1 RT1.prd
M3 2 RT1.prd,1
M2 1 ASD.prd
M3 2 ASD.prd,2
M2 1 PDG.prd
M3 2 PDG.prd,2
M2 1 ID1.prd
M3 2 ID1.prd,1
M2 1 GDR.prd
M3 2 GDR.prd,2
M2 1 KE1.prd
M3 2 KE1.prd,1
M2 1 IG1.prd
M3 2 IG1.prd,1
M2 1 V4I.prd
M3 2 V4I.prd,2
M2 1 COM.prd
M3 2 COM.prd,2
M2 1 CO1.prd
M3 2 CO1.prd,1
M2 1 CC1.prd
M3 2 CC1.prd,1
M24 1 E5I.prd
M3 2 E5I.prd,1
EOF
fRR3+V/9ZoBxxsd0Uyxslh+JDDxMRcU1Q4lJRdtuK4+aLZSt18UbeklX+ny+5fWgChZoCUUV1f8t/Ie4pHWPwQ/67Jdi98QqidX07016gz2smPFbwnm+RN5jl4sfrsr7Z8ebyvBCiEpFhLq6khvdhNhaXtnVIq2r+ms4kkSQdWOi22DXmDBJgV+nvMqu/qda9sHn9KexEUhS6ikPlIukZw98KqwKoHwSDpGUDfjRF+jNW79wnsD8v18iskhhR1927td9qrw4Mun+3WFDaI41w74t/U/MnfF54ZIBcQXgnCqSpEV96NgOkI7ozV7VbwRYwgpiaSuBGR1h80tI4nCPRQ==
