<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 CAI - SmarTeam - CATIA Integration Product
M6 1 200
M7 1 1
M9 1 Shareable
EOF
HtdQCmM6nr2pceiATgG2Y8RxElGf+NS3ItejyVebmwXE+q/LemVAWVlyla9KBZLs7a5BsGYWhnXEapokWXmrdfE//GOFowMyPAbeazq/2sfN5979qIdRZ4dwL1b/cx5YlDS5tw/9Jh5blYOjNbrURlMyUMnyTjKIBHs6opb29Xia9zfHghODoGoMk1Fh44+IDeYaFYpjuuFczfNM5a6NgnKSJSZchQmcv1CDUiytXiTN7W2jQSrSgkj0SgTwbE+UZ4mhRyYv1moo05Vf/lFx3HaITiJvOVHGm7fn9KhrUD4mD21mwsTJpImTxSOfYzsT6rJWOUA4RHAHZ58GP+kAzw==
