<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 CC1 - CATIA - CADAM INTERFACE 1 Product
M7 1 1
M6 1 3055
M9 1 Addon
M9 1 Shareable
M2 1 CCDModelAccess
M3 2 CCDModelAccess,1
M2 1 CCDV5Coupler
M3 2 CCDV5Coupler,1
M2 1 DraftingAnnotation
M2 1 DraftingFeature
M2 1 DraftingAnnotationModeler
M2 1 DraftingUI
M2 1 DraftingInterfaces
M1 1 ID1.prd
M2 1 DraftingInfrastructure
M3 2 DraftingInfrastructure,1
M2 1 DraftingInfrastructureUI
M3 2 DraftingInfrastructureUI,1
M2 1 DraftingBaseInfrastructure
M3 2 DraftingBaseInfrastructure,1
M2 1 DraftingBaseInfrastructureUI
M3 2 DraftingBaseInfrastructureUI,1
M2 1 CATAnnotationModeler
M3 2 CATAnnotationModeler,1
M2 1 CATAnnotationModelerUI
M3 2 CATAnnotationModelerUI,1
M2 1 CATAssemblyInterfaces
M3 2 CATAssemblyInterfaces,1
M2 1 CATPDMBase
M2 1 ENOVaultClientCPP
M2 1 CORBARuntime
M3 2 CATPDMBase,1
M3 2 ENOVaultClientCPP,1
M3 2 CORBARuntime,1
M2 1 CATProductStructurePDM
M3 2 CATProductStructurePDM,1
M2 1 CATPDMBaseUI
M3 2 CATPDMBaseUI,1
M2 1 CATPDMBaseInterfaces
M3 2 CATPDMBaseInterfaces,1
M19 1 CciEnglish
M19 1 ICONS
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
EOF
SV7uh6weroQGCJcFci8LMAHOc9qrKpYC/y5yVNVx7NP00vm6hN2FegA4/YpkFiviqd0oRpJSE1iqaIz+/EAUEQ67s6cIBODJ+E7Q78BKgGbOx5bybY48rQnEKM6sJ5GcPs0lFlnDmER8rJnK9W90Pvf9q6RA1set0eNGrjpGbGZdaGRJKQcs8FKTZTJUgq15AjtNC2qzMxw6H99urJFwri20dtsX2NrNr0Q7yTsyhlCfnLJyaxCY305GERJw7Kbo7vvfo3bbJ5ulLDOMOAkE7r+iMTUP+5DlyXmeJc9/z1m5ZnmCHRSfas9VI3yzb8c9vrJfr8x02bjnrG8QACkg0g==
