<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 CCD - CATIA - CADAM DRAFTING for V5 Product
M7 1 2
M6 1 2041
M9 1 Addon
M9 1 Shareable
EOF
gr+neZqKjR1ZPIwurML9HbNkj0grJnCvIhVyR8R8WUs3sxDTyJ/xcxjChqBjd0/zxLnkcvJIj/7/R1CDwJKXPpPk2qpfW0FvTeWeEV6X3zvp3YhHKJ2Yxu1gAeQ1e4uO6WUJRreLpEqPj65rt2Q4tTFYflyDYtkifYetIcfz9fy1GlWjeBYPDv3fRpM7DV6smpfYKQWqqU+OMeWmFER5jodnPrGGyFLvuMyE9SgIJ+5ABnJtPJ+Vjx0A/eTEyqjENojYfee5bJc5kjvO2ZIShi6/mcLAO18Dg4KtW4iNaydHwsKa+nd+CPlns0QCAQJYYktfiQDAWZrU0n4hshfEvg==
