<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M19 1 ICONS
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 CfySamples
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
M19 1 PrtEnglish
M19 1 DysEnglish
M4 1 Fillet_More_Solid
M4 1 Fillet_Limiting_Solid
M4 1 Fillet_Blend_Solid
M4 1 Fillet_Intersection_Solid
M4 1 SketchBased_Planar_Profile
M4 1 PublicationInPartDesignWorkbench
M5 1 CFO - CATIA - CAST & FORGED PART OPTIMIZER 2 Product
M7 1 2
M6 1 2858
M9 1 Addon
M9 1 Shareable
M2 1 SketcherUI3D
M3 2 SketcherUI3D,2
M1 1 PDG.prd
M19 1 CfoEnglish
M4 1 CFP_LimitedSewing
M4 1 CFP_DraftFitted
M4 1 CFP_CliffEdgeVariableFillet
M4 1 CFO_Autofillet_CreateEdit
M4 1 CFO_Autofillet_Update
M4 1 CFO_EdgeFilletParting
M4 1 CFO_DraftBothSidesUI
M4 1 CFO_SmoothingDeviation
M4 1 CFO_FaceFilletKeepEdge
M4 1 CFO_AutoDraft_CreateEdit
M4 1 CFO_AutoDraft_Update
M4 1 CFO_WallThicknessAnalysis_CreateEdit
M4 1 CFO_WallThicknessAnalysis_Update
EOF
UZz1KLSkhc8KtiQZz6uTjh8kr4dN8b+msgBjocuu0+E5YxSdnCddWYSLTqjmn+TOmRJgpGl7coaqnR1d2z3EpkYJePGlvQyAAkXBeUm4HQea5aDW1eneCJSGVv1EGL+dBZV1hx1vi9AQxpdIQaQP2JuMD09ydb10AOnmXLpk9tGJf8+hzs+Ny2lGO8dzD/7epgyRsFhFZNz8hKwvewyt28Xl3N00Nldbn4QbfBVBJpQHZO/xy49iZsJV5tCdBY/gJsydrCVr7q89BM2mtOv/8nxuA8I5yZtwd9xnNlnVJ3sP37EkHvn3dMJb4Y/J3ZYzzUrStxRVDTR7jgzwa9GXgg==
