<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 COM - CATIA - OBJECT MANAGER 2 Product
M7 1 2
M6 1 2115
M1 1 CO1.prd
M3 2 ApplicationFrame,2
M3 2 CATIAApplicationFrame,2
M3 2 Dialog,2
M3 2 Graph,2
M3 2 PictoGraphic,2
M3 2 Visualization,2
M3 2 VisualizationBase,2
M3 2 FeatureCommands,2
M3 2 PictoGraphicBase,2
M2 1 XOM.prd
M3 1 XOM.prd
M2 1 XOH.prd
M3 1 XOH.prd
EOF
GawFK3GxubrKCfWMexevLLWUwS0NJxrWp6r3p7hNiVu8C6BVLDUbWobxRM/h38Y29c7RvsTWMDJJEVMzjDyK+QmxV7MCp0cSqZIUncy8PJ6hQBB1lWTT2kwGm2M4vwqLqOAmQffGQpXKHlsZvRD63zuThD7jfWKyGG2vWdLh50KBeSVFNRhsCYGPdro2VQYOAnU//+wk9tIeVz+cLFvIqOdQAcspsms1YaeDVjt2VqDpRSsVSyC8bgVfYGxBKlfdjBLNQuLIwHA5m0aG2ytnpMT+AFLEroTX2G6iHg4BebAlDplLY/f/reOaMiwgW+ExASmLPlNlDtlg4mZ+5wTFmQ==
