<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 CV2 - CATIA - CORE & CAVITY DESIGN 2 Configuration
M7 1 2
M6 1 2581
M2 1 CCV.prd
M3 2 CCV.prd,2
M2 1 HA1.prd
M3 2 HA1.prd,1
M2 1 GS1.prd
M3 2 GS1.prd,2
M2 1 IG1.prd
M3 2 IG1.prd,1
M2 1 V4I.prd
M3 2 V4I.prd,2
M2 1 COM.prd
M3 2 COM.prd,2
M2 1 CO1.prd
M3 2 CO1.prd,1
M2 1 RT1.prd
M3 2 RT1.prd,1
M2 1 AS1.prd
M3 2 AS1.prd,1
M2 1 PD1.prd
M3 2 PD1.prd,1
M2 1 ID1.prd
M3 2 ID1.prd,1
M2 1 GDR.prd
M3 2 GDR.prd,2
M2 1 KE1.prd
M3 2 KE1.prd,1
M2 1 ST1.prd
M3 2 ST1.prd,1
M24 1 E5I.prd
M3 2 E5I.prd,1
EOF
ctSGy+aPg6maa8eJ2qqL34TECBu4KT3thhthkAJtNSiHKHVqguDs/+cMsdG5buw3L9F2XPNSw5/FX7uEdUXagZkEOOWA0IzyYjBb+MGcmPbUJwPtO4kwcB6tMTrw/B20U63sMN+fAag/KchQ6hFuy/n+fe6r0DF+fhhmIBJsZ7pzTVnsQdhWht8mPSyd0MVRAv7YCk9BOPGjsYy+4Uq2BG4CVgzL1C13aoo7/nCcmst1rYZbH7bn1baAuUfQ2lUFrdy5qJDreO7dFBy6MTqNHdHc0qe6zRbuRUqVFEMPHi59gipOBol20jbfpb5yRfvi3KfJ+YM77v9dNQOxvivmQg==
