<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 EX2 - CATIA - Educational Heat EAR 2 Configuration
M6 1 3352
M7 1 2
M2 1 XL2.slt
M3 2 XL2.slt,2
M24 1 E5I.prd
M3 2 E5I.prd,1
M4 1 AO_Education
EOF
XDjkFiZGezh1UTQ+MUy003q/746ohOxeyTggFdJxdhrAtLWf+N0+V67sNgrWDo94C92QqP0uYtPxRMd+wXxGP8Vatql1zK2u2nHAJZbynGvQcyKvhngvMM9BymFY/oyWtCDl6MuagSKY+hArq1Qmzu77YthhEo4+if251D4HNgnATA08vEs47MizuB7JUYsmbd0VF5KdjDABhFJCfIF8S8LUQRnAu1lnjvIsNuQpTedj1o4Kvl6L3kMewFsAZE+eG1P056QdIjn6JvuedWqk1G9gYsavs+oGqL7JsAAnk59tGdn8WMwyJqSLT+yiaXpsQPw+9oly4CGwO4O3NA9STQ==
