<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 FSO - CATIA - FREESTYLE OPTIMIZER 2 Product
M7 1 2
M6 1 2112
M9 1 Addon
M9 1 Shareable
M4 1 SDS_WorkOnSupport3D_Authorized
M3 2 FreeStyleConfiguration,3
M3 2 FreeStyleShapeInterface,3
M3 2 FreeStyleShapeUI,3
M3 2 FreeStyleShapeModel,3
M3 2 FreeStyleAnalysisInterface,3
M3 2 FreeStyleAnalysisUI,3
M3 2 FreeStyleAnalysisModel,3
M3 2 FreeStyleResources,3
M3 2 CAAFreeStyleItf,3
M3 2 CATSurfacicResources,3
M3 2 CATSurfacicUIResources,3
M3 2 CATSurfacicInterfaces,3
M3 2 FreeStyleConstraintSolver,3
M3 2 CATClassACoreInterfaces,3
M3 2 CATClassACoreResources,3
M2 1 ProductStructureDocument
M3 2 ProductStructureDocument,2
M1 1 FSS.prd
M19 1 FssEnglish
M19 1 ICONS
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 CfySamples
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
EOF
jbeP0PUtlZu5yLiE66voew33U2uKAYtS4iZfgDF+YpVIUHuRWPKX/Kvinxz0QfWeABvkDRui4kGLXtM1TbMisi3n1NkXmcq96KF+a8QvagxpvNGNu1znqhQMJmXhVMilllpR8/2vy4pLlzR1iCJh8o5upcq1jXorJiGkf66ua/rD1EdB0h8WamHNn2MDCmOZSHNxNx+bk7wMPuvm75sOWUZ6i6JlEqw0XCZiuGjhBcaMZVH5G1gceqUfUclBX6/JlejpJRibwCzwglqfuv3+jgPg1szM/Lb0ttfHnqcm4xDiY2AReE8CIUpINEeCz0bSozVlmC/m/5pmsp4kZnlOOA==
