<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 GAS - CATIA - GENERATIVE ASSEMBLY STRUCTURAL ANALYSIS 2 Product
M7 1 2
M6 1 2024
M9 1 Addon
M9 1 Shareable
M1 1 GPS.prd
M11 1 AnalysisConnection
M2 1 CATAnalysisConnectionUI
M3 2 CATAnalysisConnectionUI,2
M2 1 ProductStructureUI
M3 2 ProductStructureUI,2
M2 1 ProductStructureDocument
M3 2 ProductStructureDocument,2
M4 1 MSH_Weld
M4 1 LSA_ApplyMat_OnConnection
M4 1 LSA_Connection
M4 1 LSA_Weld_Connection
M4 1 LSA_Interface_Connection
M4 1 LSA_Slider_ConProperty
M4 1 LSA_Contact_ConProperty
M4 1 LSA_Fastened_ConProperty
M4 1 LSA_PressureFitting_ConProperty
M4 1 LSA_Bolt_ConProperty
M4 1 LSA_Distant_ConProperty
M4 1 LSA_VirtualBolt_ConProperty
M4 1 LSA_UserDefined_ConProperty
M4 1 LSA_Weld_ConProperty
M4 1 LSA_Interface_ConProperty
M4 1 LSA_Assembly_Prepro
M4 1 LSA_Assembly_Solution
M4 1 LSA_Solution_Case
M4 1 SIM_AssemblyCreation
M4 1 SIM_AssemblyViewer
M4 1 SIM_InsertComponent
EOF
ej+9ruFwjZbKrCxOoEb25nECs2Kq7kpdkl/u0DWaStGeByVriYYvbJWf5lnqjvuABdTE1zgYYAPmC4we13A841dczSV6ekEvA5JddbasLw/BZabqwWa26vJwRtOC7wmWxynwwABOPEYhhHPekREoBZV90wIx9eZTEjWTTYbHM+bDWgiSYGv6zCHs60Cesl3yiu5ioyKZK4uggPVIdH81RJVl+CAkVw0LsjoHrVYX9orJU/rKOdR1aAquI0j2KJFJ601lH+QF8zCxkWpXT6/cYXQV+hrLsMwPpJFT0/Qx70TW5dRhzlJio1tYABtofrye3pjVtfmVAQ96gjahXgbHrQ==
