<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 HPC - HUMAN POSTURE CATALOG 2 Product
M6 1 3303
M7 1 2
M9 1 Addon
M9 1 Shareable
M2 1 DNBHumanPostureCatalogs
M3 2 DNBHumanPostureCatalogs,2
M1 1 HBR.prd
EOF
YOrDzqBdARJy/Pu7GrwCOm2OGlsK+bIyJ0h9/X7UcsPvE5cWCpQzzmlDdwJcqTem5knMsedlRJEgZrvqe95k+tv/4Go5hvBzQETKG078ctqrxhXc0wLY1j82hsVM3eqDmSym4+GeN3HZfB0iqC+iSsJLtfcGt287U2nZCQyz9tesFEXIS2PEuP9Ar6kRkJaZLyj3z9k21UuXS2Jtnss1MwU6TlhOBuyzvx3Tq0gJAPX9y1tqHdTGmbzuyGUuyT7iwsuk1M1ZjS64SGfWj+wSxleeh8Urqkui8BDtv+42v++1pSXh10xF2UPP3NcfHB6ir7T0G4GFsDdc9u1Rf6aX+A==
