<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 ISX - CATIA - ICEM Shape DESIGN CENTER & EXPERT 2 Configuration
M6 1 3389
M7 1 2
M2 1 IEX.prd
M3 2 IEX.prd,2
M2 1 ICM.prd
M3 2 ICM.prd,2
M2 1 FSS.prd
M3 2 FSS.prd,2
M2 1 GS1.prd
M3 2 GS1.prd,2
M2 1 TXG.prd
M3 2 TXG.prd,2
M2 1 ST1.prd
M3 2 ST1.prd,2
M2 1 V4I.prd
M3 2 V4I.prd,2
M2 1 IG1.prd
M3 2 IG1.prd,2
M2 1 COM.prd
M3 2 COM.prd,2
M2 1 CO1.prd
M3 2 CO1.prd,1
EOF
CtGZoyJ0vDXHclWR7eYEngdc1oNNgXWq/qlB866IkBFDrhuwpElI1/foqwg2siqowy0ZHL9/zAd0HZ6eWnoB876JrxFGoGr1Ug5OTRcjVhQijHoHrP+zSeoxk018IzBkalg5D8RRpnCtOqgAkCTIZ445Lyozc+ZYfpRTP4wv6fDJJreM6NKCKxsPjK79ILCJ2Wua+1mjF8nPFDadu/mBn8qtoKnAtOWlxlGYpl4uKF3x9iMP0LiswqL28vYZqNfycM0lvKVc/c/zdrkgZqyPMkaiZZ+eqbiv9s7bNNoKPYV5b8FoHtmQvC0ccaNwJx1Wfnpa9XO/xFUQhqh5bzrpkw==
