<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 LG1 - CATIA - LATHE MACHINING 1 Product
M7 1 1
M6 1 2423
M9 1 Addon
M1 1 NG1.prd
M11 1 WSPROC
M11 1 CATALOGWorkshop
M11 1 PRDWorkshop
M11 1 LatheProgramWorkbench
M11 1 PrsConfiguration
M2 1 LatheMachiningInterfaces
M3 2 LatheMachiningInterfaces,1
M2 1 CATLatheMachInterfaces
M3 2 CATLatheMachInterfaces,1
M2 1 CATLatheMach
M3 2 CATLatheMach,1
M2 1 CATLatheMachUI
M3 2 CATLatheMachUI,1
M2 1 CATMfgLatheMachiningAlgos
M3 2 CATMfgLatheMachiningAlgos,1
M2 1 PrismaticMachining
M3 2 PrismaticMachining,1
M2 1 PrismaticMachiningInterfaces
M3 2 PrismaticMachiningInterfaces,1
M2 1 Marker
M3 2 Marker,1
M2 1 SIMSequenceModel
M3 2 SIMSequenceModel,1
M2 1 MillingNCCSToolPath
M3 2 MillingNCCSToolPath,1
M2 1 SIMInterfaces
M3 2 SIMInterfaces,2
M2 1 SIMPlayer
M3 2 SIMPlayer,2
M19 1 LmgEnglish
M19 1 MfgEnglish
M19 1 PmgEnglish
M19 1 ICONS
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 CfySamples
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
M2 1 DNBDptIPMNavigation
M3 2 DNBDptIPMNavigation,1
M2 1 DNBDptIPMNavigationInterfaces
M3 2 DNBDptIPMNavigationInterfaces,1
M2 1 CATTTRSInterfaces
M3 2 CATTTRSInterfaces,1
M2 1 CATCameraInterfaces
M3 2 CATCameraInterfaces,1
EOF
bIHgwjvl5o195jDwuJCrn59f67TG+gaxv+a6OGc1klqcEE8aWIrn+wzcNHpYdsiv5tfjHX9Sn645UJrOaAUA2U4Iyux7gJvcJ+ykfi6bnMQ4qqkxmVkszcu0nDabzBftMnmFjrofOHdzMM3nb7TDeblPnxd+wYaXasC9S2jyVfF9QOCJejSKHX686AWio9xBWAqzm5vccUhPWKdjtQYROulOLaqkMFI3OGsbyygSZMVS91tAf2MOT767GPYhCJpjkmpN8W4gKiuGRImKTt2RcwHBdGi/jlviwV6+caOzoGsqpdQu8QD8AMZ0PA+KNn2kxdBkfQ8YXk4uGZNctS+d3A==
