<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 MD2 - CATIA - MECHANICAL DESIGN 2 Configuration
M7 1 2
M6 1 2119
M2 1 GS1.prd
M3 2 GS1.prd,1
M2 1 KE1.prd
M3 2 KE1.prd,1
M2 1 RT1.prd
M3 2 RT1.prd,1
M2 1 ASD.prd
M3 2 ASD.prd,2
M2 1 PDG.prd
M3 2 PDG.prd,2
M2 1 GDR.prd
M3 2 GDR.prd,2
M2 1 IG1.prd
M3 2 IG1.prd,1
M2 1 V4I.prd
M3 2 V4I.prd,2
M2 1 ID1.prd
M3 2 ID1.prd,1
M2 1 COM.prd
M3 2 COM.prd,2
M2 1 CO1.prd
M3 2 CO1.prd,1
M2 1 CC1.prd
M3 2 CC1.prd,2
M24 1 E5I.prd
M3 2 E5I.prd,1
EOF
O64nu3ahIYew0QlTwZbiVgz4qnpRt2aBc5t9bjZzDxqwO7IQ02lcu2bxcSQHHxYc5xooLT6whkmZcHKVd8oRdoAU8G6e01rIlZOFxHcq2lZf36fFNuj+l37hCMCQFEUjpsWiQELlpzMcoo33zVQmTR5P9PQlQReu06mpHyojQSxcavl2u6oRv3Z6Z79gzg8zUhsjf6aBJge3m6jTEe3++jKmU/VC4Ai5/CpmQlIDNYo/0WEzbs16UAIvM76ZTiYmPLymeO4SJxbnowcD/3H6fg7i5fu6yLw3L+Otr3DSTqoJdpX1dtmYFgmRA1p6TTFmv232vrRYhizTmMu7TZd6eQ==
