<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 MLG - MULTI-SLIDE LATHE MACHINING 2 Product
M6 1 2923
M9 1 Addon
M9 1 Shareable
M7 1 2
M1 1 LMG.prd
M11 1 WSPROC
M11 1 CATALOGWorkshop
M11 1 PRDWorkshop
M11 1 PrsConfiguration
M2 1 CATMfgAdvLatheMachining
M3 2 CATMfgAdvLatheMachining,2
M2 1 CATMfgAdvLatheMachiningItf
M3 2 CATMfgAdvLatheMachiningItf,2
M2 1 DNBDpmBase
M3 2 DNBDpmBase,2
M2 1 DNBMOBuild
M3 2 DNBMOBuild,2
M2 1 DNBTBRBuild
M3 2 DNBTBRBuild,2
M4 1 DNBSimulateMachining
M19 1 MlgEnglish
M19 1 LmgEnglish
M19 1 MfgEnglish
M19 1 PmgEnglish
M19 1 ICONS
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 CfySamples
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
M2 1 DPMSettingsInterfaces
M3 2 DPMSettingsInterfaces,2
EOF
SvsNLPRQXpo4hDf05QzptFyTsxvCMZmsFLFt0eYx/N9c1Kil5UMalNvNGql8vaTC2NVV4RcDCCDhMO1gUSdvoFixnIJjBkW3azWOQGToSPsYrNe0OACWl4ukYgqoLu5YB0zWJoFY6xrApfSrssAKNqfVh1ptEj/Hz36cFKv0OIUIsTwkj+lmfgSrRnpYnZzuW3o3v4CR+pF8TOJbU9U/uNRYxkL3mNJhJRO7rfJ+1w6WlgZrJCoB7K0Xd8zoZOn7Vpt4IuA57mMqh590JvZDpikfaHZg+IRHZb8uMVYk1GIiAQAQqBIS6Zk4e1i1/6ajTcFcqIglxwv73voZbBMkqw==
