<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 MPA - CATIA - PRISMATIC MACHINING PREPARATION ASSISTANT 2 PRODUCT
M6 1 2671
M9 1 Addon
M9 1 Shareable
M7 1 2
M1 1 NCG.prd
M11 1 WSPROC
M11 1 CATALOGWorkshop
M11 1 PRDWorkshop
M11 1 PrsConfiguration
M2 1 GSSMachiningFRUI
M3 2 GSSMachiningFRUI,2
M2 1 CATMfgAdvPartMachining
M3 2 CATMfgAdvPartMachining,2
M2 1 CATMfgMultiAxisOperations
M3 2 CATMfgMultiAxisOperations,2
M2 1 LatheMachiningInterfaces
M3 2 LatheMachiningInterfaces,2
M2 1 MillingAdvancedToolPath
M3 2 MillingAdvancedToolPath,2
M2 1 MillingNCCSToolPath
M3 2 MillingNCCSToolPath,2
M2 1 MachinistOpeInfra
M3 2 MachinistOpeInfra,2
M2 1 MachinistOperations
M3 2 MachinistOperations,2
M2 1 SurfaceMachiningInterfaces
M3 2 SurfaceMachiningInterfaces,2
M2 1 CATLatheMachInterfaces
M3 2 CATLatheMachInterfaces,2
M2 1 SurfaceMachiningAlgoInterfaces
M3 2 SurfaceMachiningAlgoInterfaces,2
M19 1 MpaEnglish
M19 1 MfgEnglish
M19 1 PmgEnglish
M19 1 NcgEnglish
M19 1 ICONS
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 CfySamples
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
M2 1 CATCloudImportExport
M3 2 CATCloudImportExport,2
M2 1 MachinistCommands
M3 2 MachinistCommands,2
EOF
MmFSBK9JU3yJj68Ass7iP9cogOff1b6KJDvMQHswLGWfsj5fpORCSQ2yJ8sT28MG8grrDL1/A0DleHlLuE+ReW7GpQkCIBrywhLc0F+fgGnh7naSb6xlepgJJv2ysU9g7/Cxqq2XrAT07f/NKalOt+iZ8loTMkkMMD3BAHwJ8eIEBHdzTYubheQJt6O02IaLO8bL/9zvnSGrKYHoD84ZwvjU2LFykh7bRHllT0/KGi0iF+lR0W1+gnA9leM+Iw+twmr2kBdfgv7r1FVE9PzKws3BBVMYqRwe8fgA5FVPgK9fmMKEn9llYJuc723QHEOz5ZvvHQKBbe0VwjeotyfO5w==
