<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 NVG - CATIA - NC VERIFICATION 2 Product
M7 1 2
M6 1 2570
M9 1 Addon
M9 1 Shareable
M1 1 NCG.prd
M2 1 DNBZipNVG
M3 2 DNBZipNVG,2
M19 1 NvgEnglish
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 MfgEnglish
M19 1 ICONS
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
EOF
SKQPaLqzABNcz+oZNJmCsV9FlFQjuuiyog5gQhyk3soAvDhBkr33ukG6JM5f2DKjYOleNdiw/CFAXNhTCahZ4sGgQjJWXUxYyixfExN5dadleJF38DcVowwthQg6HsjPInVW75WYtt8nWalYJtvxrKS+A1UWMnfY758nhJvHI5ZSdm+7N6SAriPT9wwQ5nWzNxBjFAdg3GYXSTpujMh2nJHB1VqHpr5rtbOCaAU1iRryn4+Xdg4yn4WyCg4WKmzph6RKFXIf5MgOTZ1D0+m5diW0idBPHMU3TIuBF0xhEOjdXLxtsKevZBRXdY8q462zGmvr2MTjBb/plky7HEpVGg==
