<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 PSO - Photo Studio Optimizer 2 Product
M6 1 2607
M9 1 Addon
M9 1 Shareable
M7 1 2
M11 1 CATALOGWorkshop
M11 1 MaterialWorkshop
M11 1 PRDWorkshop
M11 1 PrsConfiguration
M11 1 RenderingWorkbench
M19 1 PsoEnglish
M19 1 PhsEnglish
M19 1 ICONS
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 CfySamples
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
M1 1 PHS.prd
EOF
KNg4c6140uxcXk4vp8AJOS5pK2VuOvoAHR5x+obuPoTTTP+VB+ADr+H3f/PH6n1vzqD/tBOoNT5GVNe0okvpktV/t2JNTSee1btcg++E9qQ/2vnzwf2NMEH+lpvw4sbVfGyYnzNE1PHbNfs4PD7uE0y5B3jgO2Xa32asbEpX2DQW46N5ifEjhaD1gG34P+1apUmP+KBSxHuJrrlzz0BQuxFqD/DHo9gz6EPc+I/1QQfnH7TiNQLOfweuARLlfS2Nj2oGBnSNYNz5k2GKzO1v6spRU5a2ALAVH3Uhrttml18oQt5orWZdGQypaEUy9INOr9d409TSHU+wx3WTYVAQbA==
