<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 PX1 - CATIA - PPR PDM Gateway 1 Product
M7 1 1
M6 1 2556
M9 1 Addon
M9 1 Shareable
M1 1 CO1.prd
M4 1 AO_PPR_PDM_Gateway
M2 1 CATxPDM
M3 2 CATxPDM,1
M2 1 CATxPDMInterfaces
M3 2 CATxPDMInterfaces,1
M2 1 CATxPDMSendTo
M3 2 CATxPDMSendTo,1
M2 1 ProductStructureUI
M13 1 CATxPDMInterfaces
M15 1 CATxPDMInterfaces
M17 1 CAAxPDMInterfaces.edu
M14 1 CAAxPDMInterfacesDoc.edu
M13 1 PartInterfaces
M13 1 ProductStructure
M13 1 CATGraphicProperties
M13 1 KnowledgeModeler
M13 1 ProductStructureUI
M13 1 LiteralsEditor
M15 1 PartInterfaces
M15 1 ProductStructure
M15 1 CATGraphicProperties
M15 1 KnowledgeModeler
M15 1 ProductStructureUI
M15 1 LiteralsEditor
EOF
hsCw8NLoNEUWihTFfodUyc2IOs/cHI+yZ1lnqlmcbUPVwzka2s63qGEzkS0p3ehmTcVpBPh1QaI8tpqfGvlzQ6neGOSFcLXJfX52jMZCyBHjBSTWHHfMxqL7tyBYLqyNv2cZhwAtr8zMZgaKxpV0YE58HCsVIol/tF6CzJFbkF+Op/hW3W8ExYXUiRleg+iDo5SfJxMmPMKSZ04cWfMSOg5Lh7za86DpaTGhIo6zTPu0yzp1c2yUglxcgSIQDab6ccgUh8nxxiZy3n1/E1GSOQ9yPsJHGSCDT4IV2bHrO9Fn63gsEkzYV9q8hCGgRd1eJDSA1H4sABjon/GwikukAg==
