<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 RM2 - CATIA - PREPARATION MOLD & DIE MACHINIST 2 Configuration
M6 1 2561
M7 1 2
M2 1 GS1.prd
M3 2 GS1.prd,1
M2 1 SMG.prd
M3 2 SMG.prd,2
M2 1 PMG.prd
M3 2 PMG.prd,2
M2 1 NCG.prd
M3 2 NCG.prd,2
M2 1 RT1.prd
M3 2 RT1.prd,1
M2 1 AS1.prd
M3 2 AS1.prd,2
M2 1 PD1.prd
M3 2 PD1.prd,2
M2 1 ID1.prd
M3 2 ID1.prd,1
M2 1 GD1.prd
M3 2 GD1.prd,2
M2 1 IG1.prd
M3 2 IG1.prd,1
M2 1 V4I.prd
M3 2 V4I.prd,2
M2 1 COM.prd
M3 2 COM.prd,2
M2 1 CO1.prd
M3 2 CO1.prd,1
M2 1 CC1.prd
M3 2 CC1.prd,1
M24 1 E5I.prd
M3 2 E5I.prd,1
EOF
RYzuoFDDYwStawrwogtAZcCj6YZq8kSk75myzA9AjS1Z5Ey+a9aT60ZmdSsnARybenwkcdSgoBNLY7H0Fmtru/t4gGKhoCZHw7OlSWAxfn16kaq0G37Z3BmAiHUUsNXHeoNxIByxkuvXdoF0Pkx0oxoJWpM0iraHM3mS+d1nWjUOKbLxqfNPgYcycHAsyg0pfOYcndmqkJSL78UqQNygmIwM+gDerEcg2XsMQ8zMYud83UnCYk72/tJvmMbxC+eOBPw+akeh4xLvzZYR+pgLufPLLQDgtAsiVVXMWX9y7N9VqM1SsrsgXFTTYDP934OsqlqUhw335tm69ZwQNOytTw==
