<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 SA2 - CATIA - STRUCTURAL ANALYSIS 2 Configuration
M7 1 2
M6 1 2206
M2 1 EST.prd
M3 2 EST.prd,2
M2 1 GAS.prd
M3 2 GAS.prd,2
M2 1 GPS.prd
M3 2 GPS.prd,2
M2 1 V4I.prd
M3 2 V4I.prd,2
M2 1 COM.prd
M3 2 COM.prd,2
M2 1 CO1.prd
M3 2 CO1.prd,1
M24 1 E5I.prd
M3 2 E5I.prd,1
EOF
XWh/GJhqFcM5IgKqsAgU2wh8CrQ9PUqH/xqoHzKO9dp3n0P0E203LqoLVeiJabvddIpH/+qyOTLbhl4m3evYlNC4OaQZrgbeQthRivBC9/sRV6BI6N1UPQCxD1JP+amOGphX4Q/gv25Dk1j3uWjIfKPYhcCoH4RqRyYPl4lUe2sszk6JZddouokElgtc6dduXZaD2p3mzjJdsHUDAuH3R75n57QHc4jYi7Ig/CIK/DGlFcOFy86gxiOtBvfjZt55osI43mSy/68Nz7gq8eogtslp5/V/gNdwGhp+0/ubKPauSxTaSH4pd03yUZqWc//mAcRnCgpIctEYP3YCOxsAWA==
