<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 SXT - CATIA - EXTENDED STEP INTERFACE 2 Product
M6 1 3363
M7 1 2
M9 1 Addon
M9 1 Shareable
M4 1 STEP_Extended_Capabilities
M2 1 DataExchangeCompositesItf
M3 2 DataExchangeCompositesItf,1
M2 1 STEPDXCompositesExport
M3 2 STEPDXCompositesExport,1
M2 1 STEPDXCompositesImport
M3 2 STEPDXCompositesImport,1
M1 1 COM.prd
M1 1 ST1.prd
EOF
iKX8cSsjRyJHFETRDdU/rZ/bdPn5SNBs3x/osl45zsrvlt3YW+xV+Tc3gfhK75itvwV9RmMYNqK3NBX31LIaXuWYjOAj/VN6FAcWnAOzwPJ4Pd6zM95dsI4BvKjxQmDraTtZUQWh46+Yaz4E3PLG3yI60rtGqkKj3LGaxMlyx7SnsP/ayVuJMu/N9EpuHXNzM3xVLCKGEaZP9jANkF4UdUEkj5J/VghCtgzu305f2fLOPfGQC2W5QACbzh6bEJtYidL39JYDMWHnH8gv8Bz4IXPSTDew/DAGJdHZLHfSw8lV/3kDV3l9/3I7GaFqjp2L6z5F9KrIb1kHRa67u+YaFA==
