<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 VOA - VEHICLE OCCUPANT ACCOMMODATION 2 Product
M7 1 2
M6 1 3205
M9 1 Addon
M9 1 Shareable
M1 1 HBR.prd
M2 1 CATHumanPackaging
M3 2 CATHumanPackaging,2
M2 1 CATHumanPackagingInterfaces
M3 2 CATHumanPackagingInterfaces,2
M2 1 CATHumanPackagingUI
M3 2 CATHumanPackagingUI,2
M11 1 SWKManikinWkb
EOF
IakaV+FR0Sb0HHQuxq/mguUc/RUBRgvyQuoT5I99GYJE5Trd349iudtzBjMBBcjqVgUzK3QlRVkyF6ptZR1v0NPqdg/MGcqDENKnZQGwyoEFFDRGCbNVQwA3xKvrmvPyooUqz/yM7EecqZb0c79EHlm7oEXzMJzMM38n2R1C+HXu5SQS34o8StwEIrB5QzD7s5vmhTfZdEL1pFwrrXh8U0Q3XPwOSrRUy4rJd4faovkd0CKhcSJh55RyJsxXk+xz4ixXRrj/UyXiSCp1NeOKgIX8B54A+uCSFUw37EAu7nAzsi0xruTgiM77smZc3Wk79As7x7mlndK5TcN1n70RTQ==
