<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 WD1 - CATIA - WELD DESIGN 1 Product
M6 1 2573
M9 1 Addon
M9 1 Shareable
M7 1 1
M1 1 AS1.prd
M11 1 CATEAsdWeldWorkbench
M2 1 CATAsdWeldUI
M3 2 CATAsdWeldUI,1
M2 1 CATAsdWeldCmd
M3 2 CATAsdWeldCmd,1
M2 1 CATAsdWeldInterfaces
M3 2 CATAsdWeldInterfaces,1
M2 1 CATAsdWeldModel
M3 2 CATAsdWeldModel,1
M2 1 CATAsdJointCmd
M3 2 CATAsdJointCmd,1
M2 1 CATAsdJointInterfaces
M3 2 CATAsdJointInterfaces,1
M2 1 CATAsdJointModel
M3 2 CATAsdJointModel,1
M2 1 CATAsdJointServices
M3 2 CATAsdJointServices,1
M19 1 Wd1English
M19 1 AsmEnglish
M19 1 FdtEnglish
M19 1 KwrEnglish
M19 1 PrtEnglish
M19 1 PstEnglish
M19 1 SdgEnglish
M19 1 ICONS
M19 1 BasEnglish
M19 1 CfyEnglish
M19 1 CfySamples
M19 1 CAAScriptDoc.edu
M19 1 CAAScriptResourcesDoc.edu
M19 1 Programation
EOF
PKTZ9C6bvam9vLJyAZF3fbtsmxsHBAlaWcLOh2p3s7XlBU6UzeumBcVx3S2zeBysGeQSIa2jkul8GZ5MZNjQzguP88+VOta+FHr2W5wXFQqmcXE6dh1wtRf8lmcPPPiBHHFd9i14ssEGwWWDB2AZRMoN/HYVvnPdPecUVZUL4l9sMvfXjkWfoZAmU5j+MABUBY2B+u8TbaVLyM2VH/LBYJqyInf2ZPALTzVy5zTsZRZirf3lq/igPCGWgTz/clxT3ZyGVzGR9lIZv8RSMb1Yz3+ujUAbBg6y6iQUIqePiYON6nGpf2CC0aT/uqTcryn55lY+gwccHaEaaAtAn47aNA==
