<I.C SCRIPT>  WINNT 10
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 XM2 - CATIA - EXTENDED MECHANICAL DESIGN 2 Configuration
M7 1 2
M6 1 2549
M2 1 RT1.prd
M3 2 RT1.prd,1
M2 1 ASD.prd
M3 2 ASD.prd,2
M2 1 SMD.prd
M3 2 SMD.prd,2
M2 1 PDG.prd
M3 2 PDG.prd,2
M2 1 ID1.prd
M3 2 ID1.prd,1
M2 1 GDR.prd
M3 2 GDR.prd,2
M2 1 KE1.prd
M3 2 KE1.prd,1
M2 1 ST1.prd
M3 2 ST1.prd,1
M2 1 IG1.prd
M3 2 IG1.prd,1
M2 1 V4I.prd
M3 2 V4I.prd,2
M2 1 COM.prd
M3 2 COM.prd,2
M2 1 CO1.prd
M3 2 CO1.prd,1
M2 1 GS1.prd
M3 2 GS1.prd,2
M2 1 WD1.prd
M3 2 WD1.prd,1
M2 1 CC1.prd
M3 2 CC1.prd,1
M24 1 E5I.prd
M3 2 E5I.prd,1
EOF
X65oHqb6ywbq7Qgsye66g889hkSIVayolav0pACW6Jp3wXYJtrWT9RHxyeSVEkg4tuAvIGK1/xvxgJ7pXN0nnOdC8ZBGSFN/arVFxO0nzil5ZQvRDNP+3qDtfsWvfZg3TkYl27yb0QJLKn67bIeNlJJ8H3YBmE25BPEwp3QlTrYRVDZLLiGCjoSz4ggaHaQS13hDSDj/aurcpIdovfngcHgXPFHuB2XDj+zngbTnnzvp/90jDoN/A7D7+x9x5+eYT+f0fKXIyPhX4xsBY0VMmNnv6dAa/k0N80lyA+UlaK59zGS5+335Uck4KVixv8anmpKXuqRaO0bn1eOeasyZxQ==
