<I.C SCRIPT>  WINNT 6
M10 1 "Dassault Systemes" "Copyright Dassault Systemes 1999-2011"
M21 1 052100
M5 1 Z7Z - CATIA - New product Menu Item NOT MARKETTED
M7 1 2
M6 1 2508
M11 1 PRDWorkshop
M11 1 PrsConfiguration
M2 1 ProductStructureDocument
M3 2 ProductStructureDocument,2
M2 1 ProductStructureUI
M3 2 ProductStructureUI,2
EOF
D9t308N6FGzd2vm3bTtJoUbA3zhdktZhklfH/gNHa270UJUC61wbJhwL370D4J8FbjS5stUC7B3SAJra9MJnD8Dk0jYzkKFg0lK+f7d3XYJmP8V93QiwLG9+VhH0UFqj8nTR00tHajsxZ8J37emNwOUnV/5NiCBDHK2RXM9vjZkGUh+m94c25uX/BR3uaYcv0qBjBWtlzzYihxd1x3Gb+XyOyPTvmRkeMLZp3Cu4rVMubqD+cbTTi6gzLIt7gSmJbui33GmCoS+i5jyxxleLI/xj2aKBKXEj+AW/bqsa1fnN1OkyZxJCRtm9aOjjJIhwb2D9qnoHAbkL0QEMc5MKhQ==
